sudo: false
language: python
python:
- 2.7
addons:
  apt:
    packages:
    - ansible
install:
- pip install ansible-lint
script:
- ansible-lint -t '!ANSIBLE0010' *.yml playbooks/*.yml
- ansible-galaxy install -r requirements.yml -p roles/
- ansible-playbook -i hosts --syntax-check $(ls *.yml | grep -v requirements.yml)
notifications:
  slack:
    secure: qs2pA0ECZjHH6bNNEzOOs6c3nITPDgJx2ZaoEE+58HiEqmxHuVAP/8DMfF6qXb4Q2ARzTeQhR/E8coShWzSinFuBVyKlzJCySs+/rHacBI02fzOR2aVJDGgQayy5FENICK2YB6FI62Jh2NpPsPFa/r2ATvuSmtWjFQ9+g6rs8HimvjDePsYHW7hr1HMKenzF/PsWxlctB9P1PM/nhSvXRGErA59zyIepw4MvRh5Wd9zUNPQS8WxVPhKeywbN7piNFB4XQaCJBbH04sM13LISEkEV/rlnSeujMj4V99BNkACQ1MrChh8GFyI/pKXnHqbRl0koB8n+WVAj6B2b6iEM4RG7ljXjhRWp8UR0VwTsl1a0QjaLJRyFaRom+oEQydKZrvnMuqEzguW6yMSlwJCr2Yo3hv/8PpD9kAqLbtMEzEAOb1q3Dvene5GIiWc85r8tG3/Ucw7GRurQXVQqyRgbxmdpx6sQgjF6rzzlauKxGeCFE/+hL7ZQnoU9W89o9477ZuNFoMmt+Tc0fS5hfa3Pg3ETz37izQu6UhDalqG+2MOhVo+Fb6WSUgPRQNcPxfjj9sFCBg9N9b8O4HyGV7sBECle/D20M4X5+efWfrxE6FyWTHNTJSRpVj5ZinKCN8nMkHzazSy6kT0OaOUH4TOpLxHp5FNO+mijhTZirhXwzxE=
