---
- hosts: arm
  become: true
  become_method: sudo
  # gather_facts: no
  # vars:
  #   MAILTO: drew@invadelabs.com

  tasks:
  - include: playbooks/initial.yml # etckeeper, fail2ban, ansible bits
  - include: playbooks/sshd_config.yml # sshd_config
  - include: playbooks/pkgs_debian.yml # all software bits needed

  - name: arm; drew-piv3; apt; install fail2ban
    apt: name=fail2ban state=present # update_cache=yes
    when: ansible_hostname == "drew-piv3"

  - include: playbooks/postfix_relay.yml # sendgrid relay config
  - include: playbooks/nrpe.yml

  # - include: playbooks/postfix.yml # sendgrid relay config
  # - include: playbooks/drive.yml # initalize drive, configures letsencrypt
  # - include: playbooks/letsencrypt.yml # setup certbot
  # - include: playbooks/apache2.yml # a2enmod, a2ensite, apache2.conf
  # - include: playbooks/deploy_invadelabs.com.yml # initial invadelabs.com deploy
  # - include: playbooks/deploy_drew.invadelabs.com.yml # DrewWiki depoy with googleAnalytics, OpenGraphMeta, Descript2, lock down versions
  - include: playbooks/cron.yml
  - name: Notify message to place apache_env, github_token, postfix_password, and slacktee.conf
    debug:
      msg: "Create /root/{apache_env,github_token,postfix_password,slacktee.conf}"

  handlers:
  - name: Start postfix.service
    service: name=postfix state=started enabled=yes

  - name: Restart nrpe.service
    service: name=nagios-nrpe-server state=restarted
  - name: Restart sshd.service
    service: name=sshd state=restarted
  - name: Restart postfix.service
    service: name=postfix state=restarted

  roles:
  # - { role: tersmitten.swapfile, swapfile_size: 1GB, swapfile_swappiness: 10 } # XXX run this last
  # - { role: mongrelion.docker, userland-proxy: false }
