---
- hosts: drew-serv
  become: true
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Add user drew
    user:
      name: drew
      uid: 1000 # 1001 on invadelabs, fix this

  - name: Add drew to sudoers
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^drew ALL='
      line: 'drew ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'

  - name: Add docker-ce repo
    command: sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    args:
      creates: /etc/yum.repos.d/docker-ce.repo

  - name: Install Base Packages
    dnf: name={{item}} state=present
    with_items:
    - docker-ce
    # base
    - chrony
    - mcelog
    - lldpd
    - samba
    - httpd
    - screen
    - git # for github.com/invadelabs/cron-invadelabs
    - bc # for github.com/invadelabs/cron-invadelabs
    - bind-utils # for dig
    - dnf-plugins-core # for docker install
    - snapd # for drive
    # python
    - python-dnf # for ansible
    - python2-pip # for ansible docker module
    - python2-virtualenv # for ansible docker module
    - libselinux-python # for ansible
    # nagios
    - nrpe
    - nagios-plugins-users
    - nagios-plugins-load
    - nagios-plugins-disk
    - nagios-plugins-procs
    # qemu-kvm
    - qemu-kvm
    - libvirt
    - virt-install
    - bridge-utils
    - libguestfs-tools
    notify:
    - Start docker
    - Start chronyd
    - Start mcelog
    - Start lldpd
    - Start smb
    - Start nmb
    - Start httpd
    - Start nrpe
    - Start libvirtd

  - name: git clone invadelabs.com/cron-invadelabs
    git:
      repo: https://github.com/invadelabs/cron-invadelabs.git
      dest: /root/scripts
      depth: 1

  - name: Install docker-py pip module
    pip:
      name: docker-py

  - name: Install drive via snap
    command: snap install drive --classic
    args:
      creates: /var/lib/snapd/snap/bin/drive

  # when / if this fails drive is not initialized! `cd /root; drive init`
  - name: Get latest backup of nagios backup
    shell: /var/lib/snapd/snap/bin/drive pull -piped $(/var/lib/snapd/snap/bin/drive ls Backup/Web | grep nagios-drewserv | grep -v sha256 | sort | tail -n 1 | cut -c 2-) > /home/drew/nagios-bkup-latest.tar.xz
    args:
      chdir: /root
      creates: /home/drew/nagios-bkup-latest.tar.xz
    notify:
    - Extract nagios-bkup-latest.tar.xz
    - Create container nagios4

  - name: Add cron check_ddns.sh
    cron:
      name: check_ddns.sh
      minute: "*/5"
      user: root
      job: /root/scripts/check_ddns.sh

  - name: Add cron gdrive_backup.sh
    cron:
      name: gdrive_backup.sh
      minute: "0"
      hour: "6"
      user: root
      job: /root/scripts/gdrive_backup.sh -a nagios-drewserv -d /var/lib/snapd/snap/bin -f Backup/Web -l gdrive_backup_nagios-drewserv.txt -s

  - name: Add cron check_docker.sh
    cron:
      name: check_docker.sh
      minute: "*/1"
      user: root
      job: /root/scripts/check_docker.sh

  handlers:
   - name: Start docker
     service: name=docker state=started enabled=yes
   # base
   - name: Start chronyd
     service: name=chronyd state=started enabled=yes
   - name: Start mcelog
     service: name=mcelog state=started enabled=yes
   - name: Start lldpd
     service: name=lldpd state=started enabled=yes
   - name: Start smb
     service: name=smb state=started enabled=yes
   - name: Start nmb
     service: name=nmb state=started enabled=yes
   - name: Start httpd
     service: name=httpd state=started enabled=yes
   # nagios
   - name: Start nrpe
     service: name=nrpe state=started enabled=yes
   # kvm
   - name: Start libvirtd
     service: name=libvirtd state=started enabled=yes

   - name: Extract nagios-bkup-latest.tar.xz
     unarchive:
       src: /home/drew/nagios-bkup-latest.tar.xz
       dest: /home/drew
       remote_src: yes

   - name: Create container nagios4
     docker_container:
       name: nagios4
       image: jasonrivers/nagios:latest
       state: started
       volumes:
         - /home/drew/nagios/etc:/opt/nagios/etc
         - /home/drew/nagios/var/opt/nagios/var
         - /home/drew/nagios/Custom-Nagios-Plugins:/opt/Custom-Nagios-Plugin
       ports:
         - "0.0.0.0:8080:80"