---
- hosts: invadelabs.com
  become: true
  become_method: sudo
  # gather_facts: no
  vars:
    rsyslog_host: localhost
    rsyslog_port: 11514
    nrpe_allowed_hosts: "nm.invadelabs.com,127.0.0.1,::1"

  tasks:
  - name: fail if hostname not set to invadelabs.com
    fail:
      msg: "Host name is not set to invadelabs.com! Run; hostnamectl set-hostname invadelabs.com"
    when: ansible_fqdn != "invadelabs.com"

  - include: playbooks/preflight_check.yml # fail if missing secrets
  - include: playbooks/initial.yml # etckeeper, fail2ban, ansible bits
  - include: playbooks/pip.yml # anything pip here
  - include: playbooks/pkgs_debian.yml # all apt / dpkg software bits needed
  - include: playbooks/sshd_config.yml # sshd_config
  - include: playbooks/logging.yml # rsyslog / filebeat
  - include: playbooks/postfix.yml # sendgrid relay config
  - include: playbooks/drive.yml # initalize rclone, configures letsencrypt
  - include: playbooks/letsencrypt.yml # setup certbot
  - include: playbooks/apache2.yml # a2enmod, a2ensite, apache2.conf
  - include: playbooks/deploy_invadelabs.com.yml # initial invadelabs.com deploy
  - include: playbooks/deploy_drew.invadelabs.com.yml # DrewWiki depoy with googleAnalytics, OpenGraphMeta, Descript2, lock down versions
  - include: playbooks/cron.yml
  - include: playbooks/nrpe.yml # sshd_config

  handlers:
  - include: playbooks/service_handlers.yml # start / restart systemd stuff

  - name: apache2; set env variables
    shell: grep {{a2env_vars_item}} /root/apache_env | awk -F '"' '{print $2}'
    with_items:
      - deploy_env
      - email_env
      - slack_env
    loop_control:
      loop_var: a2env_vars_item
    register: apache_env_vars # XXX Fix this for invadelabs.com.conf.j2 temlate
    no_log: true
    notify: apache2; add site templates

  #- debug:
  #    msg: "{{ apache_env_vars.results[0].stdout }}"

  # apahce2 vhosts
  - name: apache2; add site templates
    template:
      src: templates/etc/apache2/sites-available/{{a2temp_item}}.conf.j2
      dest: /etc/apache2/sites-available/{{a2temp_item}}.conf
    with_items:
      - drew.invadelabs.com
      - invadelabs.com
      - www.invadelabs.com
    no_log: true
    loop_control:
      loop_var: a2temp_item
    notify:
      - apache2; a2ensite templates
      - Restart apache2.service

  # XXX https://github.com/ansible/ansible-modules-extras/pull/1240 use this module when finished
  - name: apache2; a2ensite templates
    command: a2ensite {{a2ensite_item}}
    args:
      creates: /etc/apache2/sites-enabled/{{a2ensite_item}}.conf
    with_items:
      - drew.invadelabs.com
      - invadelabs.com
      - www.invadelabs.com
    loop_control:
      loop_var: a2ensite_item
    notify: Restart apache2.service

  # roles:
  # - { role: tersmitten.swapfile, swapfile_size: 1GB, swapfile_swappiness: 10 } # XXX run this last
  # - { role: mongrelion.docker, userland-proxy: false }
