---
- hosts: invadelabs.com
  become: true
  become_method: sudo
  # gather_facts: no
  # vars:
  #   MAILTO: drew@invadelabs.com

  tasks:
  - include: playbooks/etckeeper.yml
  - include: playbooks/initial.yml
  - include: playbooks/sshd_config.yml
  - include: playbooks/pkgs.yml
  # configure sendgrid + domain whitelisting
  # configure lets encrypt
  - include: playbooks/apache2.yml # XXX add mod_pagespeed, more loops
  # invadelabs.com deploy
  # DrewWiki depoy with googleAnalytics, OpenGraphMeta, Descript2, lock down versions
  - include: playbooks/cron.yml

  - name: Notify message to place github_token, mediawiki_to_git_md, and slacktee.conf
    debug:
      msg: "Create /root/{slacktee.conf,github_token,mediawiki_to_git_md}"

  handlers:
   - name: Start apache2.service
     service: name=apache2 state=started enabled=yes
   - name: Start postfix.service
     service: name=postfix state=started enabled=yes

   - name: Restart sshd.service
     service: name=sshd state=restarted
   - name: Restart apache2.service
     service: name=apache2 state=restarted

  roles:
  - { role: tersmitten.swapfile, swapfile_size: 1GB, swapfile_swappiness: 10 } # XXX run this last
  # - { role: mongrelion.docker, userland-proxy: false }
