---
- hosts: invadelabs.com
  become: true
  become_method: sudo
  tasks:
  - include: playbooks/initial.yml
  #- include: playbooks/sshd_config.yml
  - include: playbooks/web_pkgs.yml
  #- include: playbooks/postfix.yml # configure sendgrid + domain whitelisting
  # configure lets encrypt
  # configure apache2 modules rewrite, headers, mod_pagespeed
  # configure apache2 sites
  # invadelabs.com deploy
  # DrewWiki depoy with googleAnalytics, OpenGraphMeta, Descript2, lock down versions
  # a2ensite /apache2 reload
  # create /root/{slacktee.conf,slacktee.sh,gen_sitemap.sh,wiki_to_md.sh}
  #- include: playbooks/swapfile.yml
  # lynis
  # configure crons
  roles:
    - { role: mongrelion.docker, userland-proxy: false }
