---
- hosts: nm1
  become: true
  become_method: sudo
  # gather_facts: no
  vars:
    rsyslog_host: "192.168.1.125"
    rsyslog_port: "10514"
    nrpe_allowed_hosts: "192.168.1.0/24,172.17.0.0/16,127.0.0.1,::1"

  tasks:
  - include: playbooks/preflight_check.yml # fail if missing secrets

  - include: playbooks/initial.yml # etckeeper, fail2ban, ansible bits

  # - include: playbooks/pkgs_fedora.yml # XXX fix python2-dnf requirement for fedora 30
  #   when: ansible_os_family == "RedHat"
  - include: playbooks/pkgs_debian.yml
    when: ansible_os_family == "Debian"

  - include: playbooks/pip.yml

  - include: playbooks/firewall.yml
  - include: playbooks/logging.yml

  - include: playbooks/hw_drew-serv.yml # hardware specifics
    when: ansible_host == "drew-serv"
  - include: playbooks/drive.yml # google drive bits
    when: ansible_host == "drew-serv"
  - include: playbooks/mount.yml
    when: ansible_host == "drew-serv"
  - include: playbooks/samba.yml
    when: ansible_host == "drew-serv"
  - include: playbooks/httpd.yml
    when: ansible_host == "drew-serv"

  - include: playbooks/postfix.yml
    when: ansible_host == "drew-serv"
  - include: playbooks/postfix_relay.yml
    when: (ansible_host == "drew-pine64") or ( ansible_host == "drew-piv3" ) or ( 'rpi-cluster' in group_names )

  - include: playbooks/ntop.yml # hardware specifics
    when: ansible_host == "drew-piv3"

  - include: playbooks/nut_ups.yml # hardware specifics
    when: ansible_host == "drew-piv3"

  - include: playbooks/rpi-cluster.yml
    when: "'rpi-cluster' in group_names"

  - include: playbooks/docker.yml
  - include: playbooks/sshd_config.yml
  - include: playbooks/nrpe.yml
  - include: playbooks/cron.yml

  # docker containers; if this fails drive is not initialized! `cd /root; drive init`
  - name: docker; get drew-serv-bkup-latest.tar.xz backup
    shell: |
      P="/var/lib/snapd/snap/bin"
      $P/drive pull \
      -piped "$($P/drive ls Backup/Web | grep drew-serv | \
      grep -v sha256 | sort | tail -n 1 | cut -c 2-)" > \
      /srv/drew-serv-bkup-latest.tar.xz
      touch /var/log/docker-init.touch
    args:
      chdir: /root
      creates: /var/log/docker-init.touch
    when: ansible_host == "drew-serv"
    notify:
    - docker; extract drew-serv-bkup-latest.tar.xz
    - docker; create container nagios4
    - docker; create container gitlab
    - docker; create container nightscout
    - docker; create container bind

  handlers:
  - include: playbooks/service_handlers.yml # start / restart systemd stuff

  ## Misc Handlers
  - name: Setup lm_sensors
    command: sensors-detect --auto # XXX not when modules have already been inserted
  - name: grub2-mkconfig -o /boot/grub2/grub.cfg
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
  - name: systemd daemon-reload
    systemd: daemon_reload=yes
  - name: resolvconf -u
    command: resolvconf -u
  - name: update-alternatives; editor vim-basic
    alternatives:
      name: editor
      path: /usr/bin/vim.basic
    when: ansible_os_family == "Debian"
  - name: Run sysctl
    command: sysctl -p

  ## Docker Handlers
  - name: docker; extract drew-serv-bkup-latest.tar.xz
    unarchive:
      src: /srv/drew-serv-bkup-latest.tar.xz
      dest: /srv
      remote_src: yes
      # system_u:object_r:container_file_t
      setype: container_file_t
      serole: object_r
      seuser: system_u
    when: ansible_host == "drew-serv"

  - name: docker; create container nagios4
    docker_container:
      name: nagios4
      image: jasonrivers/nagios:4.4.2 # 4.3.4, 4.4.1
      state: started
      restart_policy: unless-stopped
      hostname: nagios.invadelabs.com
      log_driver: json-file
      log_options:
        max-size: "10m"
      volumes:
        - /srv/nagios4/etc:/opt/nagios/etc
        - /srv/nagios4/var:/opt/nagios/var
        - /srv/nagios4/Custom-Nagios-Plugins:/opt/Custom-Nagios-Plugins
        - /srv/nagios4/nagiosgraph/var:/opt/nagiosgraph/var
        - /srv/nagios4/nagiosgraph/etc:/opt/nagiosgraph/etc
        - /srv/nagios4/main.cf:/etc/postfix/main.cf
        - /srv/nagios4/nagios.conf:/etc/apache2/sites-available/nagios.conf
      env: {
        "MAIL_RELAY_HOST": "192.168.1.125",
        "NAGIOS_FQDN": "nagios.invadelabs.com",
        "NAGIOS_TIMEZONE": "America/Denver"
        }
      ports:
        - "0.0.0.0:8080:80/tcp"
    when: ansible_host == "drew-serv"

#    # https://docs.gitlab.com/runner/install/docker.html
#  - name: docker; create container gitlab
#    docker_container:
#      name: gitlab
#      image: gitlab/gitlab-ce:latest # 10.8.2 / 10.8.2-ce.0
#      state: stopped # XXX
#      restart_policy: unless-stopped
#      hostname: gitlab.invadelabs.com
#      log_driver: json-file
#      log_options:
#        max-size: "10m"
#      volumes:
#        - /srv/gitlab/config:/etc/gitlab
#        - /srv/gitlab/logs:/var/log/gitlab
#        - /srv/gitlab/data:/var/opt/gitlab
#        - /etc/letsencrypt:/etc/letsencrypt:ro
#      ports:
#        - "0.0.0.0:9443:443/tcp"
#        - "0.0.0.0:9980:80/tcp"
#        - "0.0.0.0:9922:22/tcp"
#    when: ansible_host == "drew-serv"

  - name: docker; create container nightscout
    docker_container:
      name: nightscout
      image: drewderivative/nightscout:2019.03.10
      state: started
      restart_policy: unless-stopped # XXX orig issue cannot bind to interface on startup, so start on cron
      hostname: nightscout.invadelabs.com
      log_driver: none
      log_options:
        max-size: "10m"
      ports:
        - "0.0.0.0:1337:1337/tcp"
      env_file: /root/my.env
    when: ansible_host == "drew-serv"

  - name: docker; create container bind
    docker_container:
      name: bind
      image: sameersbn/bind:9.10.3-20180127
      state: started
      restart_policy: unless-stopped # XXX orig issue cannot bind to interface on startup, so start on cron
      hostname: ns.invadelabs.com
      log_driver: json-file
      log_options:
        max-size: "10m"
      volumes:
        - /srv/bind:/data
      ports:
        - "192.168.1.125:53:53/tcp"
        - "192.168.1.125:53:53/udp"
        - "0.0.0.0:10000:10000/tcp"
    when: ansible_host == "drew-serv"
