---
- hosts: all
  become: true
  become_method: sudo
  tasks:
  - include: playbooks/initial.yml
  - include: playbooks/install_python.yml
  - include: playbooks/web.yml
  - include: playbooks/ssh.yml
  - include: playbooks/swapfile.yml
  roles:
    - { role: mongrelion.docker, userland-proxy: false }
