---
  nrpe_plugins_dir: "/usr/lib/nagios/plugins"
  nrpe_specific:
    - check_load: "{{nrpe_plugins_dir}}/check_load -r -w 4,2,1 -c 6,4,2"
    - check_total_procs: "{{nrpe_plugins_dir}}/check_procs -w 200 -c 250"
    - check_zombie_procs: "{{nrpe_plugins_dir}}/check_procs -w 1 -c 2 -s Z"
    # - check_rsyslogd_procs: "{{nrpe_plugins_dir}}/check_procs -C 'rsyslogd' -c 1"
    - check_memory: "{{nrpe_plugins_dir}}/check_memory -u M -w 20% -c 10%"
    - check_uptime: "{{nrpe_plugins_dir}}/check_uptime -f -c 10"
    - check_root: "{{nrpe_plugins_dir}}/check_disk -w 25% -c 10% -p /"
    - check_apt: "{{nrpe_plugins_dir}}/check_apt -l -t 60"
    - check_temp: "/usr/local/bin/check_temp.sh -d /sys/class/thermal/thermal_zone0/temp -w 65 -c 80"
    - check_fail2ban: "{{nrpe_plugins_dir}}/check_fail2ban.sh -w 1 -c 2"
    - check_ups: "{{nrpe_plugins_dir}}/check_ups -H localhost -u cyberpower1"
    - check_dns_local: "{{nrpe_plugins_dir}}/check_dns -s 192.168.1.125 -H drew-serv.nm1.invadelabs.com -w 0.5 -c 1"
    - check_dns_remote: "{{nrpe_plugins_dir}}/check_dns -s 192.168.1.1 -H google.com -w 0.5 -c 1"
