---
  monitor_containers:
    # - pihole
    # - nightscout
    - docker-elk_elasticsearch_1
    - docker-elk_kibana_1
    - docker-elk_logstash_1
    - grafana
    - homeassistant
    - influxdb
    - mosquitto
    - nexus
    - nginx
    - ring-mqtt
    - zigbee2mqtt
    - zoneminder
  nrpe_plugins_dir: "/usr/lib/nagios/plugins"
  nrpe_specific:
    - check_load: "{{nrpe_plugins_dir}}/check_load -r -w 10,6,4 -c 20,10,5"
    - check_total_procs: "{{nrpe_plugins_dir}}/check_procs -w 450 -c 475"
    - check_zombie_procs: "{{nrpe_plugins_dir}}/check_procs -w 20 -c 25 -s Z"
    # - check_rsyslogd_procs: "{{nrpe_plugins_dir}}/check_procs -C 'rsyslogd' -c 1:2"
    - check_memory: "/usr/local/bin/check_memory.pl -u M -w 20% -c 10%"
    - check_uptime: "{{nrpe_plugins_dir}}/check_uptime -w 10:"
    - check_disk: "{{nrpe_plugins_dir}}/check_disk -w 20% -c 10% -p / -p /var/lib/docker -p /mnt/share -p /srv"
    - check_apt: "{{nrpe_plugins_dir}}/check_apt -l -t 60"
    - check_temp: "/usr/local/bin/check_temp.sh -d /sys/class/thermal/thermal_zone0/temp -w 90 -c 99"
    - check_es_mem: "/usr/local/bin/check_es_system.sh -H localhost -t mem -d 4"
    - check_es_disk: "/usr/local/bin/check_es_system.sh -H localhost -t disk -d 20"
    - check_es_readonly: "/usr/local/bin/check_es_system.sh -H localhost -t readonly"
    - check_es_status: "/usr/local/bin/check_es_system.sh -H localhost -t status"
    - check_smart_sda: "/usr/local/bin/check_smart.pl -d /dev/sda -i auto -w Reallocated_Event_Count=5"
    - check_smart_sdb: "/usr/local/bin/check_smart.pl -d /dev/sdb -i auto"
    - check_smart_sdc: "/usr/local/bin/check_smart.pl -d /dev/sdc -i auto"
    - check_bat: "/usr/local/bin/check_bat"
    - check_docker: "sudo /usr/local/bin/check_docker --uptime 120:120 --connection /run/docker.sock --present --status running --containers {{monitor_containers | join(' ')}}"
    - check_mongo_mybg: "/usr/local/bin/check_mongo_mybg.py /etc/default/cgm.env 14400"
    - check_iostat: "/usr/local/bin/check_iostat -d sda -i -p"
    - check_eth: "/usr/local/bin/check_eth -i {{ ansible_default_ipv4.alias }} -w 70m -c 80m"
    - check_systemd: "/usr/local/bin/check_systemd -w 100"
    - check_ups: "{{nrpe_plugins_dir}}/check_ups -H localhost -u cyberpower1"
    - check_fail2ban: "/usr/local/bin/check_fail2ban.sh -w 1 -c 2"
  postfix_mynetworks: "172.17.0.0/16 192.168.1.0/24 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"
  host_pkgs:
    - rclone
    - docker.io
    - autossh
    - rsync
    - rasdaemon # mcelog replacement
    - smartmontools
    - rclone
    - bc
    - wget
    - samba
    - screen
    - upower
    - nethogs
    - nut
    - nut-server
    - nut-client
    - fail2ban
    - lm-sensors
    # - powertop # energy management
    - python3-certbot-dns-cloudflare
  host_pip:
    - check-docker
    - pymongo
    - dnspython # needed for mongodb+srv uri
    - cloudflare-ddns
