---
  nrpe_lib: "/usr/lib64"
  nrpe_specific:
    - check_load: "{{nrpe_lib}}/nagios/plugins/check_load -r -w 10,6,4 -c 20,10,5"
    - check_total_procs: "{{nrpe_lib}}/nagios/plugins/check_procs -w 350 -c 375"
    - check_memory: "/usr/local/bin/check_memory.pl -u M -w 10% -c 20%"
    - check_uptime: "/usr/lib64/nagios/plugins/check_uptime -c 10:"
    - check_root: "{{nrpe_lib}}/nagios/plugins/check_disk -w 20% -c 10% -p /"
    - check_updates: "{{nrpe_lib}}/nagios/plugins/check_updates -t 60"
