---
  monitor_containers: []
  nrpe_plugins_dir: "/usr/lib/nagios/plugins"
  nrpe_specific:
    - check_disk: "{{nrpe_plugins_dir}}/check_disk -w 20% -c 10% -p / -p /var/lib/docker"
    - check_docker: "sudo /usr/local/bin/check_docker --uptime 120:120 --connection /run/docker.sock --present --status running --containers {{monitor_containers | join(' ')}}"
    - check_eth: "/usr/local/bin/check_eth -i {{ ansible_default_ipv4.alias }} -w 70m -c 80m"
    - check_fail2ban: "/usr/local/bin/check_fail2ban.sh -w 1 -c 2"
    - check_iostat: "/usr/local/bin/check_iostat -d sda -i -p"
    - check_load: "{{nrpe_plugins_dir}}/check_load -r -w 10,6,4 -c 20,10,5"
    - check_memory: "{{nrpe_plugins_dir}}/check_memory -w 80% -c 90%"
    - check_smart_sda: "/usr/local/bin/check_smart.pl -d /dev/sda -i auto"
    - check_systemd: "/usr/local/bin/check_systemd -w 100"
    - check_temp: "/usr/local/bin/check_temp.sh -d /sys/class/thermal/thermal_zone2/temp -w 90 -c 99"
    - check_total_procs: "{{nrpe_plugins_dir}}/check_procs -w 450 -c 475"
    - check_ups: "{{nrpe_plugins_dir}}/check_ups -H localhost -u apc2"
    - check_uptime: "{{nrpe_plugins_dir}}/check_uptime -w 10:"
    - check_zombie_procs: "{{nrpe_plugins_dir}}/check_procs -w 20 -c 25 -s Z"
  postfix_mynetworks: "172.17.0.0/16 192.168.1.0/24 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"
  host_pkgs:
    # - powertop # energy management
    - apt-show-versions # Lynis PKGS-7394
    - autossh
    - bc
    - docker.io
    - fail2ban
    - lm-sensors
    - nethogs
    - nut
    - nut-client
    - nut-server
    - podman
    - python3-docker
    - rasdaemon # mcelog replacement
    - rclone
    - rclone
    - rsync
    - samba
    - screen
    - smartmontools
    - upower
    - wget
    - wireless-tools
  host_pip:
    - check-docker
    - dnspython # needed for mongodb+srv uri
    - podman-compose
