---
  nrpe_plugins_dir: "/usr/lib/nagios/plugins"
  nrpe_specific:
    - check_load: "{{nrpe_plugins_dir}}/check_load -r -w 4,2,1 -c 6,4,2"
    - check_total_procs: "{{nrpe_plugins_dir}}/check_procs -w 200 -c 250"
    - check_zombie_procs: "{{nrpe_plugins_dir}}/check_procs -w 1 -c 2 -s Z"
    # - check_rsyslogd_procs: "{{nrpe_plugins_dir}}/check_procs -C 'rsyslogd' -c 1"
    - check_memory: "{{nrpe_plugins_dir}}/check_memory -u M -w 20% -c 10%"
    - check_uptime: "{{nrpe_plugins_dir}}/check_uptime -f -c 10"
    - check_disk: "{{nrpe_plugins_dir}}/check_disk -w 25% -c 10% -p /"
    - check_apt: "{{nrpe_plugins_dir}}/check_apt -l -t 60"
    - check_temp: "/usr/local/bin/check_temp.sh -d /sys/class/thermal/thermal_zone0/temp -w 60 -c 65"
    - check_fail2ban: "{{nrpe_plugins_dir}}/check_fail2ban.sh -w 1 -c 2"
    - check_ups: "{{nrpe_plugins_dir}}/check_ups -H localhost -u cyberpower1"
    - check_eth: "/usr/local/bin/check_eth -i {{ ansible_default_ipv4.alias }} -w 70m -c 80m"
    - check_systemd: "/usr/local/bin/check_systemd"
  host_pkgs: []
