---
  nrpe_plugins_dir: "/usr/lib/nagios/plugins"
  nrpe_specific:
    - check_disk: "{{nrpe_plugins_dir}}/check_disk -w 25% -c 10% -p /"
    - check_eth: "/usr/local/bin/check_eth -i {{ ansible_default_ipv4.alias }} -w 70m -c 80m"
    - check_iostat: "/usr/local/bin/check_iostat -d sda -i -p"
    - check_load: "{{nrpe_plugins_dir}}/check_load -r -w 4,2,1.5 -c 6,4,2"
    - check_memory: "{{nrpe_plugins_dir}}/check_memory -w 80%% -c 90%"
    - check_systemd: "{{nrpe_plugins_dir}}/check_systemd -w 90"
    - check_temp: "/usr/local/bin/check_temp.sh -d /sys/class/thermal/thermal_zone0/temp -w 52 -c 55"
    - check_total_procs: "{{nrpe_plugins_dir}}/check_procs -w 200 -c 250"
    - check_uptime: "{{nrpe_plugins_dir}}/check_uptime -f -c 10"
    - check_zombie_procs: "{{nrpe_plugins_dir}}/check_procs -w 1 -c 2 -s Z"
  host_pkgs:
    - apt-listbugs
    - arpwatch
    - monitoring-plugins-systemd
    #- ntopng
  host_pip: []
