---
  nrpe_plugins_dir: "/usr/lib/nagios/plugins"
  nrpe_specific:
    - check_load: "{{nrpe_plugins_dir}}/check_load -r -w 4,2,1.5 -c 6,4,2"
    - check_total_procs: "{{nrpe_plugins_dir}}/check_procs -w 200 -c 250"
    - check_zombie_procs: "{{nrpe_plugins_dir}}/check_procs -w 1 -c 2 -s Z"
    - check_memory: "{{nrpe_plugins_dir}}/check_memory -b M -w 20% -c 10%"
    - check_uptime: "{{nrpe_plugins_dir}}/check_uptime -f -c 10"
    - check_disk: "{{nrpe_plugins_dir}}/check_disk -w 25% -c 10% -p /"
    - check_temp: "/usr/local/bin/check_temp.sh -d /sys/class/thermal/thermal_zone0/temp -w 52 -c 55"
    # - check_dns_local1: "{{nrpe_plugins_dir}}/check_dns -s 192.168.1.125 -H drew-serv.nm1.invadelabs.com -w 0.5 -c 1"
    # - check_dns_local2: "{{nrpe_plugins_dir}}/check_dns -s 192.168.1.120 -H drew-serv.nm1.invadelabs.com -w 0.5 -c 1"
    - check_dns_remote: "{{nrpe_plugins_dir}}/check_dns -s 192.168.1.1 -H google.com -w 0.5 -c 1"
    - check_iostat: "/usr/local/bin/check_iostat -d sda -i -p"
    - check_eth: "/usr/local/bin/check_eth -i {{ ansible_default_ipv4.alias }} -w 70m -c 80m"
    - check_systemd: "{{nrpe_plugins_dir}}/check_systemd -w 150"
  host_pkgs:
    - apt-listbugs
    - macchanger
    - monitoring-plugins-systemd
  host_pip: []
