---
  nrpe_plugins_dir: "/usr/lib/nagios/plugins"
  nrpe_specific:
    - check_load: "{{nrpe_plugins_dir}}/check_load -r -w 4,2,1 -c 6,4,2"
    - check_total_procs: "{{nrpe_plugins_dir}}/check_procs -w 200 -c 250"
    - check_memory: "{{nrpe_plugins_dir}}/check_memory -u M -w 10% -c 20%"
    - check_uptime: "{{nrpe_plugins_dir}}/check_uptime -f -c 10"
    - check_root: "{{nrpe_plugins_dir}}/check_disk -w 25% -c 10% -p /"
    - check_apt: "{{nrpe_plugins_dir}}/check_apt -t 60"
    - check_fail2ban: "{{nrpe_plugins_dir}}/check_fail2ban.sh -w 1 -c 2"
    - check_tcp11514: "{{nrpe_plugins_dir}}/check_tcp -H localhost -p 11514"
  postfix_mynetworks: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"
