---
  monitor_containers:
   - nightscout
  nrpe_plugins_dir: "/usr/lib/nagios/plugins"
  nrpe_specific:
    - check_load: "{{nrpe_plugins_dir}}/check_load -r -w 4,2,1 -c 6,4,2"
    - check_total_procs: "{{nrpe_plugins_dir}}/check_procs -w 200 -c 250"
    - check_zombie_procs: "{{nrpe_plugins_dir}}/check_procs -w 1 -c 2 -s Z"
    # - check_rsyslogd_procs: "{{nrpe_plugins_dir}}/check_procs -C 'rsyslogd' -c 1"
    - check_memory: "{{nrpe_plugins_dir}}/check_memory -u M -w 20% -c 10%"
    - check_uptime: "{{nrpe_plugins_dir}}/check_uptime -f -c 10"
    - check_disk: "{{nrpe_plugins_dir}}/check_disk -w 25% -c 10% -p /"
    - check_fail2ban: "{{nrpe_plugins_dir}}/check_fail2ban.sh -w 1 -c 2"
    - check_tcp11514: "{{nrpe_plugins_dir}}/check_tcp -H localhost -p 11514"
    - check_iostat: "/usr/local/bin/check_iostat -d sda -i -p"
    - check_eth: "/usr/local/bin/check_eth -i {{ ansible_default_ipv4.alias }} -w 70m -c 80m"
    - check_systemd: "/usr/local/bin/check_systemd"
    - check_docker: "sudo /usr/local/bin/check_docker --uptime 120:120 --connection /run/docker.sock --present --status running --containers {{monitor_containers | join(' ')}}"
  postfix_mynetworks: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"
  host_pkgs:
    - docker.io
    - rclone
    - apache2
    - libapache2-mod-php
    - php-sqlite3 # for drewwiki
    - php-mbstring # for drewwiki
    - php-xml
    - php-curl # for selenium-invadelabs script
    - php-apcu # Alternative PHP Cache (APC)
    - php7.4-fpm
  host_pip:
    - check-docker
    - docker-py
