---
  # apahce2 mods

  - name: apache2; a2enmod
    command: /usr/sbin/a2enmod {{item}}
    args:
      creates: /etc/apache2/mods-enabled/{{item}}.load
    with_items:
      - ssl
      - rewrite
      - headers
      - php7.0
    notify: Restart apache2.service

  # apahce2 env variables
  # - name: apache2; Set gitdir_env
  #   shell: grep {{item}} /root/apache_env | awk -F '"' '{print $2}'
  #   with_items:
  #     - gitdir_env
  #     - deploy_env
  #     - email_env
  #     - slack_env
  #   register: r
  # - debug: var=r
  - name: apache2; Set gitdir_env
    shell: grep gitdir_env /root/apache_env | awk -F '"' '{print $2}'
    register: gitdir_env

  - name: apache2; Set deploy_env
    shell: grep deploy_env /root/apache_env | awk -F '"' '{print $2}'
    register: deploy_env

  - name: apache2; Set email_env
    shell: grep email_env /root/apache_env | awk -F '"' '{print $2}'
    register: email_env

  - name: apache2; Set slack_env
    shell: grep slack_env /root/apache_env | awk -F '"' '{print $2}'
    register: slack_env

  # apahce2.conf
  - name: apache2.conf; ServerTokens
    lineinfile:
      dest: /etc/apache2/apache2.conf
      regexp: "^ServerTokens"
      line: "ServerTokens Prod"
      state: present
      validate: "/usr/sbin/apachectl -t -f %s"
    notify: Restart apache2.service

  - name: apache2.conf; ServerSignature
    lineinfile:
      dest: /etc/apache2/apache2.conf
      regexp: "^ServerSignature"
      line: "ServerSignature Off"
      state: present
      validate: "/usr/sbin/apachectl -t -f %s"
    notify: Restart apache2.service

  # blank /var/www/html/index.html
  - name: apache2; /var/www/html/index.html
    copy:
      dest: /var/www/html/index.html
      content: ""
    notify: Restart apache2.service

  - name: apache2; a2dissite 000-default
    command: a2dissite 000-default
    args:
      creates: /etc/apache2/sites-enabled/000-default.conf
    notify: Restart apache2.service

  # apahce2 vhosts
  - name: apache2; add site templates
    template:
      src: templates/etc/apache2/sites-available/{{item}}.conf.j2
      dest: /etc/apache2/sites-available/{{item}}.conf
    with_items:
      - drew.invadelabs.com
      - invadelabs.com
      - www.invadelabs.com
    notify: Restart apache2.service

  - name: apache2; a2ensite templates
    command: a2ensite {{item}}
    args:
      creates: /etc/apache2/sites-enabled/{{item}}.conf
    with_items:
      - drew.invadelabs.com
      - invadelabs.com
      - www.invadelabs.com
    notify: Restart apache2.service

  # - name: apache2; /etc/apache2/sites-available/drew.invadelabs.com.conf.j2 template
  #   template:
  #     src: templates/etc/apache2/sites-available/drew.invadelabs.com.conf.j2
  #     dest: /etc/apache2/sites-available/drew.invadelabs.com.conf
  #   notify: Restart apache2.service
  # - name: apache2; enable drew.invadelabs.com
  #   command: a2ensite drew.invadelabs.com
  #   args:
  #     creates: /etc/apache2/sites-enabled/drew.invadelabs.com.conf
  #   notify: Restart apache2.service

  # - name: apache2; /etc/apache2/sites-available/invadelabs.com.conf.j2 template
  #   template:
  #     src: templates/etc/apache2/sites-available/invadelabs.com.conf.j2
  #     dest: /etc/apache2/sites-available/invadelabs.com.conf
  #   notify: Restart apache2.service
  # - name: apache2; enable invadelabs.com
  #   command: a2ensite invadelabs.com
  #   args:
  #     creates: /etc/apache2/sites-enabled/invadelabs.com.conf
  #   notify: Restart apache2.service

  # - name: apache2; /etc/apache2/sites-available/www.invadelabs.com.conf.j2 template
  #   template:
  #     src: templates/etc/apache2/sites-available/www.invadelabs.com.conf.j2
  #     dest: /etc/apache2/sites-available/www.invadelabs.com.conf
  #   notify: Restart apache2.service
  # - name: apache2; enable www.invadelabs.com
  #   command: a2ensite www.invadelabs.com
  #   args:
  #     creates: /etc/apache2/sites-enabled/www.invadelabs.com.conf
  #   notify: Restart apache2.service
