---
  # apahce2 mods
  - name: apache2; a2enmod
    command: /usr/sbin/a2enmod {{item}}
    args:
      creates: /etc/apache2/mods-enabled/{{item}}.load
    with_items:
      - ssl
      - rewrite
      - headers
      - php7.2
    notify: Restart apache2.service

  # apahce2 env variables
  # - name: apache2; Set gitdir_env
  #   shell: grep {{item}} /root/apache_env | awk -F '"' '{print $2}'
  #   with_items:
  #     - gitdir_env
  #     - deploy_env
  #     - email_env
  #     - slack_env
  #   register: r
  # - debug: var=r
  - name: apache2; Set gitdir_env
    shell: grep gitdir_env /root/apache_env | awk -F '"' '{print $2}'
    register: gitdir_env

  - name: apache2; Set deploy_env
    shell: grep deploy_env /root/apache_env | awk -F '"' '{print $2}'
    register: deploy_env

  - name: apache2; Set email_env
    shell: grep email_env /root/apache_env | awk -F '"' '{print $2}'
    register: email_env

  - name: apache2; Set slack_env
    shell: grep slack_env /root/apache_env | awk -F '"' '{print $2}'
    register: slack_env

  # apahce2.conf
  - name: apache2.conf updates
    lineinfile:
      dest: /etc/apache2/apache2.conf
      regexp: "^{{item}}"
      line: "{{item}}"
      state: present
      validate: "/usr/sbin/apachectl -t -f %s"
    with_items:
      - ServerTokens Prod
      - ServerSignature Off
    notify: Restart apache2.service

  - name: apache2; add SSLStapling Cache to ssl.conf
    blockinfile:
      path: /etc/apache2/mods-available/ssl.conf
      marker: "        # {mark} ANSIBLE MANAGED BLOCK -->"
      insertbefore: "</IfModule>"
      content: "        SSLStaplingCache        shmcb:/var/run/ocsp(128000)"
    notify: Restart apache2.service

  # blank /var/www/html/index.html
  - name: apache2; /var/www/html/index.html
    copy:
      dest: /var/www/html/index.html
      content: ""
    notify: Restart apache2.service

  - name: apache2; a2dissite 000-default
    file:
      path: /etc/apache2/sites-enables/000-default.conf
      state: absent

  # apahce2 vhosts
  - name: apache2; add site templates
    template:
      src: templates/etc/apache2/sites-available/{{item}}.conf.j2
      dest: /etc/apache2/sites-available/{{item}}.conf
    with_items:
      - drew.invadelabs.com
      - invadelabs.com
      - www.invadelabs.com
    notify: Restart apache2.service

  - name: apache2; a2ensite templates
    command: a2ensite {{item}}
    args:
      creates: /etc/apache2/sites-enabled/{{item}}.conf
    with_items:
      - drew.invadelabs.com
      - invadelabs.com
      - www.invadelabs.com
    notify: Restart apache2.service
