---
## apahce2.conf
#- name: apache2; use /dev/shm for mod_pagespeed
#  lineinfile:
#    dest: /etc/apache2/mods-available/pagespeed.conf
#    regexp: "^.*ModPagespeedFileCachePath"
#    line: '    ModPagespeedFileCachePath "/dev/shm/mod_pagespeed/"'
#    state: present
#  notify: Restart apache2.service

# apahce2 mods
- name: apache2; a2dismod
  apache2_module:
    state: absent
    name: "{{a2dismod_item}}"
  with_items:
    - php7.4
    - mpm_prefork
  loop_control:
    loop_var: a2dismod_item
  notify: Restart apache2.service

- name: apache2; a2enmod
  apache2_module:
    state: present
    name: "{{a2enmod_item}}"
  with_items:
    - mpm_event
    - ssl
    - rewrite
    - headers
    #- pagespeed
    - http2
    - proxy_fcgi
    - setenvif
    - proxy_http # for cgm
  loop_control:
    loop_var: a2enmod_item
  notify: Restart apache2.service

- name: apache2; a2enconf
  command: a2enconf {{a2enconf_item}}
  args:
    creates: /etc/apache2/conf-enabled/{{a2enconf_item}}.conf
  with_items:
    - php7.4-fpm
  loop_control:
    loop_var: a2enconf_item
  notify: Restart apache2.service

- name: apache2; touch /var/log/apache-first-run.log # delete me to recreate templates
  copy:
    dest: /var/log/apache-first-run.log
    content: ""
    owner: root
    group: root
    mode: 0644
  notify: apache2; set env variables

# apahce2.conf
- name: apache2; apache2.conf updates
  lineinfile:
    dest: /etc/apache2/apache2.conf
    regexp: "^{{a2conf_item.key}}"
    line: "{{a2conf_item.key}} {{a2conf_item.value}}"
    state: present
    validate: "/usr/sbin/apachectl -t -f %s"
  with_dict: {
    'ServerTokens': 'Prod',
    'ServerSignature': 'Off'
    }
  loop_control:
    loop_var: a2conf_item
  notify: Restart apache2.service

- name: apache2; add SSLStapling Cache to ssl.conf
  blockinfile:
    path: /etc/apache2/mods-available/ssl.conf
    marker: "        # {mark} ANSIBLE MANAGED BLOCK -->"
    insertbefore: "</IfModule>"
    content: "        SSLStaplingCache        shmcb:/var/run/ocsp(128000)"
  notify: Restart apache2.service

# blank /var/www/html/index.html
- name: apache2; /var/www/html/index.html
  copy:
    dest: /var/www/html/index.html
    content: "oops"
    owner: root
    group: root
    mode: 0644

# disable default site otherwise breaks some 302 http->https
- name: apache2; a2dissite 000-default
  file:
    path: /etc/apache2/sites-enables/000-default.conf
    state: absent
  notify: Restart apache2.service

# apache-ultimate-bad-bot-blocker
- name: apache2; dl Apache_2.4.tar.gz
  get_url:
    url: https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/releases/download/V3.2021.02.1200/Apache_2.4.tar.gz
    dest: /etc/apache2/bad-bot-blocker.tar.gz
    mode: 0755
    owner: root
    group: root
    force: no
    checksum: "sha256:eb2e975bae1dd8061602037c77ffcbd1f1592ebd397887b418666f73c97314b9"

- name: apache2; extract Apache_2.4.tar.gz
  unarchive:
    src: /etc/apache2/bad-bot-blocker.tar.gz
    dest: /etc/apache2
    remote_src: yes
    owner: root
    group: root
    exclude:
      - README.md
    creates: /etc/apache2/custom.d
  notify: Restart apache2.service

- name: apache2; add bad bot blocker to conf
  blockinfile:
    path: /etc/apache2/apache2.conf
    # marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    content: |
      <Location "/">
              # AND-combine with preceding configuration sections
              AuthMerging And
              # include black list
              Include custom.d/globalblacklist.conf
      </Location>
  notify: Restart apache2.service
