---
- name: cron; check_lynis.sh
  cron:
    name: check_lynis.sh
    minute: 57
    hour: 22
    weekday: 6
    user: root
    job: /root/scripts/check_lynis.sh
  when: piv3_cluster == 0

- name: cron; ansible-pull
  cron:
    name: ansible-pull
    minute: 30
    hour: "*/2"
    user: root
    #job: ansible-pull -U https://github.com/invadelabs/ansible-invadelabs.git -o -C master -i hosts -l $(hostname -i) | systemd-cat
    job: PATH=/usr/local/bin:$PATH ansible-pull -U https://github.com/invadelabs/ansible-invadelabs.git -o -C master -i hosts -l {{ansible_host}} | systemd-cat -t ansible-pull

- name: cron; logwatch weekly
  cron:
    name: logwatch weekly
    minute: 0
    hour: 23
    weekday: 6
    user: root
    job: /usr/sbin/logwatch --output mail
  when: piv3_cluster == 0

- name: cron; cron check_letsencrypt.sh
  cron:
    name: check_letsencrypt.sh
    minute: 15
    hour: 23
    user: root
    job: /root/scripts/check_letsencrypt.sh
  when: ansible_host == "drew-serv"

- name: cron; check_ddns.sh
  cron:
    name: check_ddns.sh
    minute: "*/5"
    user: root
    job: /root/scripts/check_ddns.sh nm.invadelabs.com
  when: ansible_host == "drew-serv"

- name: cron; check_docker.sh
  cron:
    name: check_docker.sh
    minute: "*/1"
    user: root
    job: /root/scripts/check_docker.sh
  when: ansible_host == "drew-serv"

- name: cron; gen_sitemap.sh
  cron:
    name: gen_sitemap.sh
    minute: 0
    hour: 23
    user: root
    job: /root/scripts/gen_sitemap.sh -s
  when: ansible_fqdn == 'invadelabs.com'

- name: cron; gdrive_backup.sh drew-serv.invadelabs.com
  cron:
    name: gdrive_backup.sh
    minute: "0"
    hour: "23"
    user: root
    job: /root/scripts/gdrive_backup.sh -a drew-serv -d /var/lib/snapd/snap/bin -f Backup/Web -l /root/scripts/gdrive_drewserv.txt -s
  when: ansible_host == "drew-serv"

- name: cron; gdrive_backup.sh invadelabs.com
  cron:
    name: gdrive_backup.sh
    minute: 0
    hour: 23
    user: root
    job: /root/scripts/gdrive_backup.sh -a invadelabs.com -d /snap/bin -f Backup/Web -l /root/scripts/gdrive_invadelabs.com.txt -s
  when: ansible_fqdn == 'invadelabs.com'

# - name: cron; Add cron certbot
#   cron:
#     name: certbot
#     minute: 0
#     hour: 3,15
#     user: root
#     job: certbot --apache renew --quiet

- name: cron; `hostname invadelabs.com`
  cron:
    name: hostname invadelabs.com
    minute: 0
    user: root
    job: hostname invadelabs.com
  when: ansible_fqdn == 'invadelabs.com'

- name: cron; autossh
  cron:
    name: autossh
    special_time: reboot
    user: root
    job: autossh -M 0 -f -N -R 11514:192.168.1.125:10514 -R 5001:192.168.1.125:5000 -o "StrictHostKeyChecking=no" -o "PubkeyAuthentication=yes" -o "PasswordAuthentication=no" -i /home/drew/.ssh/id_rsa drew@invadelabs.com
  when: ansible_host == "drew-serv"

- name: cron; docker start bind
  cron:
    name: docker start bind
    special_time: reboot
    user: root
    job: sleep 30; docker start bind >/dev/null
  when: ansible_host == "drew-serv"

- name: cron; snapshot elasticsearch
  cron:
    name: snapshot elasticsearch
    minute: 45
    hour: "*/12"
    user: root
    job: /usr/bin/curl -sS -XPUT 192.168.1.125:9200/_snapshot/my_backup/snapshot_$(date "+\%Y.\%m.\%d-\%H:\%M:\%S\%z")?wait_for_completion=true | systemd-cat -t "elasticsearch-snapshot"
  when: ansible_host == "drew-serv"

- name: cron; backup elasticsearch snapshot
  cron:
    name: backup elasticsearch snapshot
    minute: 50
    hour: "*/12"
    user: root
    job: D=$(date '+\%Y\%m\%d\%H\%M\%S\%z'); cd /mnt/share/bkup && tar -I "pxz -T 2" --listed-incremental=docker-elk.snar -cf docker-elk.$D.tar.xz docker-elk/ && rclone copy --bwlimit 400k . --include=docker-elk.* googledrive:/Backup/elasticsearch
  when: ansible_host == "drew-serv"
