---
- name: deploy drewwiki; extract mediawiki for drew.invadelabs.com
  unarchive:
    remote_src: yes
    src: https://releases.wikimedia.org/mediawiki/1.38/mediawiki-1.38.2.tar.gz
    dest: /var/www/drew.invadelabs.com
    owner: www-data
    group: www-data
    extra_opts: ['--strip-components=1']
    creates: /var/www/drew.invadelabs.com/index.php

# XXX host this locally somewhere
#- name: drewwiki; add logo
#  get_url:
#    url: https://s6.gifyu.com/images/omgz_square.gif
#    dest: /var/www/drew.invadelabs.com/omgz_square.gif
#    owner: www-data
#    group: www-data
#    mode: 0644

# https://notepad.patheticcockroach.com/273/preventing-mediawiki-from-revealing-your-server-versions/
#- name: deploy drewwiki; remove softwareInformation SpecialVersion.php
#  lineinfile:
#    dest: /var/www/drew.invadelabs.com/includes/specials/SpecialVersion.php
#    regexp: '\$this\-\>softwareInformation\(\) \.'
#    line: '//$this->softwareInformation() .'
#    state: present

- name: deploy drewwiki; wiki_to_md.sh; git clone --depth 1 https://github.com/drew-holt/mediawiki_to_git_md.git
  git:
    repo: https://github.com/drew-holt/mediawiki_to_git_md.git
    dest: /root/mediawiki_to_git_md
    depth: 1
