---
- name: docker; ensure group "docker" exists
  group:
    name: docker
    state: present

- name: docker; append "drew" to "docker" group
  user:
    name: drew
    groups: docker
    append: true

- name: docker; add mirrors in /etc/docker/daemon.json
  template:
    src: templates/etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: Restart docker.service
  when: ansible_host == "drew-serv"

# /etc/sysconfig/docker
# +#OPTIONS='--selinux-enabled --log-driver=journald --live-restore'
# +OPTIONS='--selinux-enabled --log-driver=json-file --live-restore'

- name: docker; git clone drew-holt/docker-elk
  git:
    repo: https://github.com/drew-holt/docker-elk.git
    dest: /srv/docker-elk
    update: false #  note; setting this for initial ansible run
    version: main
  when: ansible_host == "drew-serv"

- name: docker; note to run docker compose
  debug:
    msg: "Run `cd /srv/docker-elk; docker-compose up -d` after restoring /srv/data if we fail around here."
