---
  - name: drive; Install drive via snap
    command: snap install drive --classic
    args:
      creates: /snap/bin/drive

  # when this fails drive is not initialized! `cd /root; drive init`
  - name: drive; Get invadelabs.com-bkup-latest.tar.xz backup
    shell: |
      /snap/bin/drive pull -piped $(/snap/bin/drive ls Backup/Web | grep invadelabs.com | grep -v sha256 | sort | tail -n 1 | cut -c 2-) > /home/drew/invadelabs.com-bkup-latest.tar.xz
    args:
      chdir: /root
      creates: /home/drew/invadelabs.com-bkup-latest.tar.xz

  - name: drive; Extract invadelabs.com-bkup-latest.tar.xz
    unarchive:
      src: /home/drew/invadelabs.com-bkup-latest.tar.xz
      dest: /home/drew
      remote_src: yes
      ower: www-data
      group: www-data
    args:
      creates: /var/www/data/drew_wiki.sqlite

  - name: drive; mv /home/drew/letsencrypt to /etc/letsencrypt
    command: mv /home/drew/letsencrypt to /etc/letsencrypt
    args:
      creates: /etc/letsencrypt

  - name: drive; mkdir -p /var/www/data; mv /home/drew/drew_wiki.sqlite /var/www/data
    shell:
      mkdir -p /var/www/data
      chown www-data:www-data /var/www/data
      mv /home/drew/drew_wiki.sqlite /var/www/data
    args:
      creates: /var/www/data/drew_wiki.sqlite

  - name: drive; mkdir -p /var/www/drew.invadelabs.com; mv /home/drew/LocalSettings.php /var/www/drew.invadelabs.com
    shell:
      mkdir -p drew.invadelabs.com
      chown -R www-data:www-data /var/www/drew.invadelabs.com
      mv /home/drew/LocalSettings /var/www/drew.invadelabs.com
    args:
      creates: /var/www/drew.invadelabs.com/LocalSettings.php
