---
- name: drive; get invadelabs.com-bkup-latest.tar.xz backup
  shell: |
    set -o pipefail
    FILE=$(rclone lsjson --filter '- */**' --filter '+ invadelabs.com.*.tar.xz' --filter '- *' googledrive:/Backup/Web | jq -r '.[].Name' | sort | tail -n 1)
    rclone copyto googledrive:/Backup/Web/$FILE /srv/invadelabs.com-bkup-latest.tar.xz
  args:
    chdir: /root
    creates: /srv/invadelabs.com-bkup-latest.tar.xz
  when: ansible_fqdn == 'invadelabs.com'

- name: drive; extract invadelabs.com-bkup-latest.tar.xz
  unarchive:
    src: /srv/invadelabs.com-bkup-latest.tar.xz
    dest: /srv
    remote_src: true
    creates: /var/www/data/drew_wiki.sqlite
  when: ansible_fqdn == 'invadelabs.com'

- name: drive; copy /home/drew/letsencrypt /etc/letsencrypt  # noqa deprecated-command-syntax
  shell: |
    rm -rf /etc/letsencrypt
    mv /srv/letsencrypt /etc
  args:
    creates: /etc/letsencrypt/live
  when: ansible_fqdn == 'invadelabs.com'

- name: drive; mkdir /var/www/data
  file:
    path: /var/www/data
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
  when: ansible_fqdn == 'invadelabs.com'

- name: drive; mv /home/drew/drew_wiki.sqlite /var/www/data
  shell: |
    mv /srv/drew_wiki.sqlite /var/www/data
    chown www-data:www-data /var/www/data/drew_wiki.sqlite
  args:
    creates: /var/www/data/drew_wiki.sqlite
  when: ansible_fqdn == 'invadelabs.com'

- name: drive; mkdir /var/www/drew.invadelabs.com
  file:
    path: /var/www/drew.invadelabs.com
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
  when: ansible_fqdn == 'invadelabs.com'

- name: drive; mkdir -p /var/www/drew.invadelabs.com; mv /home/drew/LocalSettings.php /var/www/drew.invadelabs.com
  shell: |
    mv /srv/LocalSettings.php /var/www/drew.invadelabs.com
    chown www-data:www-data /var/www/drew.invadelabs.com/LocalSettings.php
  args:
    creates: /var/www/drew.invadelabs.com/LocalSettings.php
  when: ansible_fqdn == 'invadelabs.com'
