---
  - name: Install drive via snap
    command: snap install drive --classic
    args:
      creates: /var/lib/snapd/snap/bin/drive

  # when this fails drive is not initialized! `cd /root; drive init`
  - name: Get invadelabs.com-bkup-latest.tar.xz backup
    shell: |
      /snap/bin/drive pull -piped $(/snap/bin/drive ls Backup/Web | grep invadelabs.com | grep -v sha256 | sort | tail -n 1 | cut -c 2-) > /home/drew/invadelabs.com-bkup-latest.tar.xz
    args:
      chdir: /root
      creates: /home/drew/invadelabs.com-bkup-latest.tar.xz
    notify:
    - Extract invadelabs.com-bkup-latest.tar.xz

  - name: mv /home/drew/letsencrypt to /etc/letsencrypt
    command: mv /home/drew/letsencrypt to /etc/letsencrypt
    args:
      creates: /etc/letsencrypt

  - name: mkdir -p /var/www/data; mv /home/drew/drew_wiki.sqlite to /var/www/data
    shell:
      mkdir -p /var/www/data
      mv /home/drew/drew_wiki.sqlite to /var/www/data
    args:
      creates: /var/www/data/drew_wiki.sqlite

  - name: mkdir -p /var/www/drew.invadelabs.com; mv /home/drew/LocalSettings.php to /var/www/drew.invadelabs.com
    shell:
      mkdir -p /var/www/data
      mv /home/drew/LocalSettings to /var/www/drew.invadelabs.com
    args:
      creates: /var/www/drew.invadelabs.com/LocalSettings.php
