---
- name: firewall; add firewalld rules
  shell: |
    firewall-cmd --permanent --zone=FedoraServer --add-masquerade
    # firewall-cmd --permanent --zone=FedoraServer --add-interface=docker0
    # firewall-cmd --permanent --zone=FedoraServer --add-rich-rule='rule family=ipv4 source address=172.17.0.0/16 accept' && firewall-cmd --reload
    firewall-cmd --permanent --zone=FedoraServer --add-service=ssh
    firewall-cmd --permanent --zone=FedoraServer --add-service=smtp
    firewall-cmd --permanent --zone=FedoraServer --add-service=http
    firewall-cmd --permanent --zone=FedoraServer --add-service=https
    firewall-cmd --permanent --zone=FedoraServer --add-service=samba
    # 5000, 5601, 10514 needed for nagios container to connect to es bridge containers
    firewall-cmd --permanent --zone=FedoraServer --add-port=5000/tcp # elasticsearch logstash/ filebeat via docker
    firewall-cmd --permanent --zone=FedoraServer --add-port=5601/tcp # elasticsearch kibana
    firewall-cmd --permanent --zone=FedoraServer --add-port=5666/tcp # nagios-nrpe
    firewall-cmd --permanent --zone=FedoraServer --add-port=10514/tcp # elasticsearch logstash / syslog via docker
    firewall-cmd --reload
    touch /var/log/firewall-first.touch
  args:
    creates: /var/log/firewall-first.touch
  when: ansible_host == "drew-serv"

# XXX ansible 2.5.2 firewalld bug https://github.com/ansible/ansible/issues/38161
# ansible 2.5.4 error below
# failed: [192.168.1.125] (item=smtp) => {"changed": false, "item": "smtp", "msg": "unsupported version of firewalld, requires >= 0.2.11"}
# - name: firewall; enable firewalld services
#   firewalld:
#     service: "{{item}}"
#     permanent: true
#     state: enabled
#   with_items:
#   - ssh
#   - http
#   - https
#   - smtp
#   when: ansible_host == "drew-serv"
#
# - name: firewall; enable firewalld ports
#   firewalld:
#     port: "{{item}}"
#     permanent: true
#     state: enabled
#   with_items:
#   - 139/tcp
#   - 445/tcp
#   - 5666/tcp
#  when: ansible_host == "drew-serv"
