---
- name: firewall; add firewalld rules
  shell: |
    firewall-cmd --add-service=ssh --permanent --zone=public
    firewall-cmd --add-service=smtp --permanent --zone=public
    firewall-cmd --add-service=http --permanent --zone=public
    firewall-cmd --add-service=https --permanent --zone=public
    firewall-cmd --add-service=samba --permanent --zone=public
    firewall-cmd --add-port=5666/tcp --permanent --zone=public # nagios-nrpe
    firewall-cmd --add-port=10514/tcp --permanent --zone=public # elasticsearch / syslog
    firewall-cmd --add-port=5000/tcp --permanent --zone=public # elasticsearch /filebeat
    firewall-cmd --reload
    touch /var/log/firewall-first.touch
  args:
    creates: /var/log/firewall-first.touch
  when: ansible_host == "drew-serv"

# XXX ansible 2.5.2 firewalld bug https://github.com/ansible/ansible/issues/38161
# ansible 2.5.4 error below
# failed: [192.168.1.125] (item=smtp) => {"changed": false, "item": "smtp", "msg": "unsupported version of firewalld, requires >= 0.2.11"}
# - name: firewall; enable firewalld services
#   firewalld:
#     service: "{{item}}"
#     permanent: true
#     state: enabled
#   with_items:
#   - ssh
#   - http
#   - https
#   - smtp
#   when: ansible_host == "drew-serv"
#
# - name: firewall; enable firewalld ports
#   firewalld:
#     port: "{{item}}"
#     permanent: true
#     state: enabled
#   with_items:
#   - 139/tcp
#   - 445/tcp
#   - 5666/tcp
#  when: ansible_host == "drew-serv"
