---
# install certs
- name: httpd; initial letsencrypt
  shell: /root/scripts/check_letsencrypt.sh
  args:
    creates: /etc/letsencrypt
  register: rclone_stat
  failed_when: rclone_stat.rc != 0 # rc = proccess exit code
  when: ansible_host == "drew-serv"
  notify: Restart httpd.service

# fedora vhosts
- name: httpd; add site templates
  template:
    src: templates/etc/httpd/conf.d/{{httpd_template_item}}.conf.j2
    dest: /etc/httpd/conf.d/{{httpd_template_item}}.conf
  with_items:
    - docker.invadelabs.com
    - drew-serv.nm1.invadelabs.com
    - cgm.invadelabs.com
    - grafana.invadelabs.com
    - ha.invadelabs.com
    - kibana.invadelabs.com
    - nexus.invadelabs.com
    - zm.invadelabs.com
  loop_control:
    loop_var: httpd_template_item
  when: ansible_host == "drew-serv"
  notify: Restart httpd.service

- name: apache2; add SSLStapling Cache to ssl.conf
  blockinfile:
    path: /etc/httpd/conf.d/ssl.conf
    marker: "        # {mark} ANSIBLE MANAGED BLOCK -->"
    insertbefore: "</IfModule>"
    content: "        SSLStaplingCache        shmcb:/var/run/ocsp(128000)"
  notify: Restart httpd.service

- name: httpd; drew-serv docroot
  template:
    src: templates/var/www/html/index.html.j2
    dest: /var/www/html/index.html
