---
- name: hw; add ip aliases
  template:
    src: templates/etc/sysconfig/network-scripts/{{item}}.j2
    dest: /etc/sysconfig/network-scripts/{{item}}
  with_items:
    - ifcfg-enp1s0:0
    - ifcfg-enp1s0:1
    - ifcfg-enp1s0:2
  notify:
    - Restart network.service

- name: hw; set /etc/default/grub nomodeset
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX="
    line: 'GRUB_CMDLINE_LINUX="rd.lvm.lv=fedora/root nomodeset"' # XXX make this dynamic fedora/root or dragons ahead
    state: present
  notify: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: hw; smartd mail root
  lineinfile:
    dest: /etc/sysconfig/smartmontools
    regexp: "^smartd_conf_opts="
    line: 'smartd_conf_opts="-H -m root"'
    state: present
  notify: Restart smartd.service
