---
  - name: hw; set /etc/default/grub nomodeset
    lineinfile:
      dest: /etc/default/grub
      regexp: "^GRUB_CMDLINE_LINUX="
      line: 'GRUB_CMDLINE_LINUX="rd.lvm.lv=fedora/root nomodeset"'
      state: present
    notify: grub2-mkconfig -o /boot/grub2/grub.cfg

  - name: hw; smartd mail root
    lineinfile:
      dest: /etc/sysconfig/smartmontools
      regexp: "^smartd_conf_opts="
      line: 'smartd_conf_opts="-H -m root"'
      state: present
    notify: Restart smartd.service
