---
- name: hw; add static ifcfg-*
  template:
    src: templates/etc/sysconfig/network-scripts/{{ifcfg_item}}.j2
    dest: /etc/sysconfig/network-scripts/{{ifcfg_item}}
  with_items:
    - ifcfg-enp1s0
  loop_control:
    loop_var: ifcfg_item
  notify:
    - Restart NetworkManager.service

- name: hw; sysctl network disable ipv6
  lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: "^{{sysctl.key}}"
    line: "{{sysctl.key}} = {{sysctl.value}}"
    state: present
  with_dict: {
    "net.ipv6.conf.all.disable_ipv6": "1",
    "net.ipv6.conf.default.disable_ipv6": "1"
    }
  loop_control:
    loop_var: sysctl
  notify:
    - Run sysctl

# XXX if enabled rd.lvm.lv= needs to be set correctly!
# - name: hw; set /etc/default/grub nomodeset
#   lineinfile:
#     dest: /etc/default/grub
#     regexp: "^GRUB_CMDLINE_LINUX="
#     line: 'GRUB_CMDLINE_LINUX="rd.lvm.lv=fedora/root rhgb nomodeset"' # XXX make this dynamic fedora/root or dragons ahead
#     state: present
#   notify: grub2-mkconfig -o /boot/grub2/grub.cfg
# - name: Set /etc/default/grub GRUB_GFXMODE
#   lineinfile:
#     dest: /etc/default/grub
#     regexp: "^GRUB_GFXMODE="
#     line: 'GRUB_GFXMODE="1024x768x32"'
#     state: present
#
# - name: Set /etc/default/grub GRUB_GFXPAYLOAD
#   lineinfile:
#     dest: /etc/default/grub
#     regexp: "^GRUB_GFXPAYLOAD="
#     line: 'GRUB_GFXPAYLOAD="1024x768x32"'
#     state: present
#
#  # only entry that adds gfxmode into grub.cfg
# - name: Set /etc/default/grub GRUB_GFXPAYLOAD_LINUX
#   lineinfile:
#     dest: /etc/default/grub
#     regexp: "^GRUB_GFXPAYLOAD_LINUX="
#     line: 'GRUB_GFXPAYLOAD_LINUX="1024x768x32"'
#     state: present

- name: hw; smartd mail root
  lineinfile:
    dest: /etc/sysconfig/smartmontools
    regexp: "^smartd_conf_opts="
    line: 'smartd_conf_opts="-H -m root"'
    state: present
  notify: Restart smartd.service
