---
# - name: hw; add static ifcfg-*
#   template:
#     src: templates/etc/sysconfig/network-scripts/{{ifcfg_item}}.j2
#     dest: /etc/sysconfig/network-scripts/{{ifcfg_item}}
#   with_items:
#     - ifcfg-enp0s25
#   loop_control:
#     loop_var: ifcfg_item
#   notify:
#     - Restart NetworkManager.service

- name: mount; mkdir /mnt/share
  file:
    path: /mnt/share
    state: directory

# - name: mount; vg_share/share
#   mount:
#     path: /mnt/share
#     src: UUID=29a687bf-2150-4825-ac20-a65c6c0a88dd
#     fstype: ext4
#     state: mounted

# when laptop lid is closed keep power on
- name: hw_drew-serv; set /etc/systemd/logind.conf
  lineinfile:
    dest: /etc/systemd/logind.conf
    regexp: "^{{logind_item.key}}="
    line: "{{logind_item.key}}={{logind_item.value}}"
    state: present
  with_dict: {
    "HandleLidSwitch": "ignore",
    "HandleLidSwitchExternalPower": "ignore",
    "HandleLidSwitchDocked": "ignore" }
  loop_control:
    loop_var: logind_item
  notify:
    - Restart systemd-logind.service

# - name: hw; set /etc/default/grub nomodeset
#   shell: grubby --update-kernel=ALL --args="nomodeset"
#
# - name: hw_drew-serv; set gfx mode /etc/default/grub
#   lineinfile:
#     dest: /etc/default/grub
#     regexp: "^{{grub_item.key}}"
#     line: '{{grub_item.key}}="{{grub_item.value}}"'
#     state: present
#   with_dict: {
#     "GRUB_GFXMODE": "1024x768x32",
#     "GRUB_GFXPAYLOAD": 1024x768x32"",
#     "GRUB_GFXPAYLOAD_LINUX": "1024x768x32" }
#   loop_control:
#     loop_var: grub_item
#   notify: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: hw; smartd mail root
  lineinfile:
    dest: /etc/sysconfig/smartmontools
    regexp: "^smartd_conf_opts="
    line: 'smartd_conf_opts="-H -m root"'
    state: present
  notify: Restart smartd.service
