---
# - name: initial; get Name cloud attribute from meta-data
#   shell: curl -s --connect-timeout .1 http://169.254.169.254/0.1/meta-data/attributes/Name || true
#   register: cloud_Name

# - name: initial; set hostname invadelabs.com
#   command: hostname invadelabs.com
#   when: 'cloud_Name.stdout == "invadelabs.com"'

- name: initial; ensure "drew" is in sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^drew ALL='
    line: 'drew ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: pkgs_debian; mkdir /root/installers
  file:
    path: /root/installers
    state: directory

- name: initial; add /etc/motd
  template:
    src: templates/etc/motd.j2
    dest: /etc/motd

- name: initial; stat /etc/localtime
  stat: path=/etc/localtime
  register: tz_localtime
# - debug:
#     msg: "{{ tz_localtime.stat.lnk_target }}"

- name: initial; set timezone
  command: timedatectl set-timezone America/Denver
  when: ( tz_localtime.stat.lnk_target != "../usr/share/zoneinfo/America/Denver" ) and ( ansible_fqdn != "invadelabs.com" )

# will be handled by gce firewall list
- name: disable sshguard
  service: name=sshguard state=stopped enabled=no
  when: ansible_fqdn == "invadelabs.com"
# - name: initial; add /etc/sshguard/whitelist
#   template:
#     src: templates/etc/sshguard/whitelist.j2
#     dest: /etc/sshguard/whitelist
#   when: ansible_fqdn == "invadelabs.com"
#   notify: Restart sshguard.service

- name: initial; drew-piv3; apt; install fail2ban
  apt: name=fail2ban state=present # update_cache=yes
  when: ansible_hostname == "drew-piv3"

- name: initial; apt; install etckeeper and initial packages
  apt: name={{int_apt_item}} state=present # update_cache=yes
  with_items:
  - etckeeper
  - python-apt # for ansible
  loop_control:
    loop_var: int_apt_item
  when: ansible_os_family == 'Debian'

- name: initial; dnf; install etckeeper
  dnf: name=etckeeper state=present
  when: ansible_distribution == 'Fedora'

- name: initial; gitconfig
  git_config:
    name: "{{git_item.key}}"
    scope: global
    value: "{{git_item.value}}"
  with_dict: {
    'user.email': 'drew@invadelabs.com',
    'user.name': 'Drew Holt'
    }
  loop_control:
    loop_var: git_item

- name: initial; set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive
  when: ansible_distribution == 'Fedora'

- name: initial; add .forward
  copy:
    dest: "{{forward_item.value}}/.forward"
    owner: "{{forward_item.key}}"
    group: "{{forward_item.key}}"
    content: "drewderivative@gmail.com"
  with_dict: {
    "drew": "/home/drew",
    "root": "/root"
    }
  loop_control:
    loop_var: forward_item
