---
# - name: initial; get Name cloud attribute from meta-data
#   shell: curl -s --connect-timeout .1 http://169.254.169.254/0.1/meta-data/attributes/Name || true
#   register: cloud_Name

# - name: initial; set hostname invadelabs.com
#   command: hostname invadelabs.com
#   when: 'cloud_Name.stdout == "invadelabs.com"'

- name: initial; ensure "drew" is in sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^drew ALL='
    line: 'drew ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: initial; ensure "nagios" is in sudoers with exact commands # XXX find a better way to do this
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^nagios ALL='
    line: 'nagios ALL = NOPASSWD: /usr/sbin/smartctl, /usr/local/bin/check_docker'
    validate: '/usr/sbin/visudo -cf %s'
  when: ansible_host == "drew-serv"

- name: initial; mkdir /root/installers
  file:
    path: /root/installers
    state: directory
    owner: root
    group: root
    mode: 0755

- name: initial; add /etc/motd
  template:
    src: templates/etc/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: initial; set timezone to America/Denver
  timezone:
    name: America/Denver

- name: initial; add rpi /etc/apt/sources.list apt proxy
  template:
    src: templates/etc/apt/sources.list.rpi.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  when: "'raspberrypi' in group_names"

- name: initial; add rpi /etc/apt/sources.list.d/raspi.list apt proxy
  template:
    src: templates/etc/apt/sources.list.d/raspi.list.rpi.j2
    dest: /etc/apt/sources.list.d/raspi.list
    owner: root
    group: root
    mode: 0644
  when: "'raspberrypi' in group_names"

#  sudo wget -O - https://packages.cisofy.com/keys/cisofy-software-public.key | sudo apt-key add -
- name: initial; add lynis gpg key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 013baa07180c50a7101097ef9de922f1c2fde6c4

- name: initial; add /etc/apt/sources.list.d/lynis.list apt proxy
  template:
    src: templates/etc/apt/sources.list.d/lynis.list.rpi.j2
    dest: /etc/apt/sources.list.d/lynis.list
    owner: root
    group: root
    mode: 0644
  when: "'debian-nm1' in group_names"

- name: initial; add /etc/apt/apt.conf.d/10periodic
  template:
    src: templates/etc/apt/apt.conf.d/10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: 0644
  when: "'debian-nm1' in group_names"

- name: initial; apt; install etckeeper and initial packages
  apt:
    pkg:
      - etckeeper
      - python3-apt # for ansible
    state: present
  when: ansible_os_family == "Debian"

- name: initial; gitconfig
  git_config:
    name: "{{ git_item.key }}"
    scope: global
    value: "{{ git_item.value }}"
  with_dict: {
    "user.email": "drew@invadelabs.com",
    "user.name": "Drew Holt"
  }
  loop_control:
    loop_var: git_item

- name: initial; add .forward
  copy:
    dest: "{{ forward_item.value }}/.forward"
    owner: "{{ forward_item.key }}"
    group: "{{ forward_item.key }}"
    mode: 0644
    content: "drewderivative@gmail.com"
  with_dict: {
    "drew": "/home/drew",
    "root": "/root"
  }
  loop_control:
    loop_var: forward_item

- name: initial; git clone --depth 1 invadelabs.com/cron-invadelabs main
  git:
    repo: https://github.com/invadelabs/cron-invadelabs.git
    dest: /root/scripts
    version: HEAD
    depth: 1

- name: initial; nrpe; dl check_memory.pl
  get_url:
    url: https://gist.githubusercontent.com/drew-holt/4da247a2874b7a0470bd3d55d5191312/raw/d24673b607dfee98f8a859acca21ef5dde26aa3d/check_memory.pl
    dest: /usr/local/bin/check_memory.pl
    mode: 0755
    owner: root
    group: root
    force: false
    checksum: "sha256:2269ac81e514a3c75dec030c5dc8d3a058729755c6cbca250e69f717a1ac7978"
  when: ansible_host == "drew-serv"

## ansi2html.sh
- name: initial; ansi2html.sh
  get_url:
    url: https://raw.githubusercontent.com/pixelb/scripts/dce7689196f6fd2efa87fd2d64e6e491c927b349/scripts/ansi2html.sh
    dest: /usr/local/bin/ansi2html.sh
    mode: 0755
    owner: root
    group: root
    force: false
    checksum: "sha256:6bff734f83234046cb94de6bff001f0038104462c5336769f09b6f0df9cc6d2e"

## slacktee.sh
- name: initial; slacktee.sh
  get_url:
    url: https://raw.githubusercontent.com/coursehero/slacktee/v1.4.2/slacktee.sh
    dest: /usr/local/bin/slacktee.sh
    mode: 0755
    owner: root
    group: root
    force: false
    checksum: "sha256:f17b39737c5fe1926c354890ac6e9e5cf11afd09d8351e9b498fe9a608cf2e95"

# check_temp.sh
- name: initial; nrpe; download check_temp.sh
  copy:
    src: /root/scripts/check_temp.sh
    dest: /usr/local/bin/check_temp.sh
    mode: 0755
    owner: root
    group: root
    remote_src: true
  when: "'nm1-hosts' in group_names"

# check_mongo_mybg.py
- name: initial; nrpe; download check_mongo_mybg.py
  copy:
    src: /root/scripts/check_mongo_mybg.py
    dest: /usr/local/bin/check_mongo_mybg.py
    mode: 0755
    owner: root
    group: root
    remote_src: true
  when: ansible_host == "drew-serv"

## check_es_system.sh
- name: initial; check_es_system.sh
  get_url:
    url: https://raw.githubusercontent.com/Napsty/check_es_system/1.8/check_es_system.sh
    dest: /usr/local/bin/check_es_system.sh
    mode: 0755
    owner: root
    group: root
    force: false
    checksum: "sha256:7cc84d9136bf31ae021bc48997167375ddbbe701c2886f74fa4d7b00abaa0242"
  when: ansible_host == "drew-serv"

## check_smart.pl
- name: initial; check_smart.pl
  get_url:
    url: https://github.com/Napsty/check_smart/raw/6.7.0/check_smart.pl
    dest: /usr/local/bin/check_smart.pl
    mode: 0755
    owner: root
    group: root
    force: false
    checksum: "sha256:d3c17702ffcde121cd990bb3e4262a7574b0034aea716e203b357abfaae94210"
  when: ansible_host == "drew-serv"

## check_bat
- name: initial; nrpe; dl check_bat
  get_url:
    url: https://raw.githubusercontent.com/drew-holt/nagios-plugins/master/check_bat
    dest: /usr/local/bin/check_bat
    mode: 0755
    owner: root
    group: root
    force: false
    checksum: "sha256:153c141744e91c4eadea1e600b253af58b81c315186d7ea2e8a1deeca9096454"
  when: ansible_host == "drew-serv"

## check_fail2ban.sh http://nagios.fm4dd.com/plugins/manual/check_fail2ban.htm
- name: initial; nrpe; dl check_fail2ban.sh
  get_url:
    url: http://nagios.fm4dd.com/plugins/source/check_fail2ban.sh
    dest: /usr/local/bin/check_fail2ban.sh
    mode: 0755
    owner: root
    group: root
    force: false
    checksum: "sha256:d51f1fbdc7ffb70a3f89dce99a54eed11c1f9b7d1605557681b80bfb407ad25d"
  when: ansible_host == "drew-serv"

- name: initial; nrpe; /var/run/fail2ban/fail2ban.sock perms
  file:
    dest: /var/run/fail2ban/fail2ban.sock
    mode: 0770
    owner: root
    group: nagios
  when: ansible_host == "drew-piv4-02"

## check_eth
- name: initial; nrpe; dl check_eth
  get_url:
    url: https://gist.githubusercontent.com/drew-holt/c716d75766c8c542b81587e5aac1ac40/raw/ae31652fff95e7b4a62962349f1400296db9d268/check_eth
    dest: /usr/local/bin/check_eth
    mode: 0755
    owner: root
    group: root
    force: false
    checksum: "sha256:b48de915ce7c9b91d5a118c21bca5df79c6983fe01ab512ab628f07808918fde"

## check_iostat
- name: initial; nrpe; dl check_iostat
  get_url:
    url: https://gist.githubusercontent.com/drew-holt/db58ae051a6923111ecec4d32cb3138d/raw/6e93b30051baf7b3b17925a341b06be61ac1ac3b/check_iostat
    dest: /usr/local/bin/check_iostat
    mode: 0755
    owner: root
    group: root
    force: false
    checksum: "sha256:24edbf321e8ee092eabd0c54f00c9568fdadf902b97dc9efbaffedc8b5c6da05"
