---
  - name: initial; set hostname
    command: hostname invadelabs.com

  - name: initial; Install initial packages
    apt: name={{item}} state=present # update_cache=yes
    with_items:
    - etckeeper
    - fail2ban
    - python-apt # for ansible

  - name: initial; Initalize etckeeper
    shell: |
      etckeeper init
      etckeeper post-install
    args:
      chdir: /etc
      creates: /etc/.git
