---
  - name: initial; set hostname
    command: hostname invadelabs.com
    when: (ansible_fqdn != "invadelabs.com") and (ansible_distribution == "Ubuntu") # XXX better bounds checking

  - name: initial; ensure "drew" is in sudoers
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^drew ALL='
      line: 'drew ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'

  - name: initial; add /etc/motd
    template:
      src: templates/etc/motd.j2
      dest: /etc/motd

  - name: initial; add /etc/sshguard/whitelist
    template:
      src: templates/etc/sshguard/whitelist.j2
      dest: /etc/sshguard/whitelist
    when: ansible_distribution == "Ubuntu"
    notify: Restart sshguard.service

  - name: initial; apt; install etckeeper and initial packages
    apt: name={{item}} state=present # update_cache=yes
    with_items:
    - etckeeper
    - python-apt # for ansible
    # - fail2ban # sshguard in ubuntu 18.04
    when: ansible_distribution == 'Ubuntu'

  - name: initial; dnf; install etckeeper
    dnf: name=etckeeper state=present
    when: ansible_distribution == 'Fedora'

  - name: initial; gitconfig
    git_config:
      name: "{{item.key}}"
      scope: global
      value: "{{item.value}}"
    with_dict: {
      'user.email': 'drew@invadelabs.com',
      'user.name': 'Drew Holt'
      }

  - name: initial; Initalize etckeeper
    shell: |
      etckeeper init
      etckeeper post-install
    args:
      chdir: /etc
      creates: /etc/.git

  - name: initial; update-alternatives editor to vim-basic
    alternatives:
      name: editor
      path: /usr/bin/vim.basic
    when: ansible_distribution == 'Ubuntu'

  - name: Set SELinux to permissive
    selinux:
      policy: targeted
      state: permissive
    when: ansible_distribution == 'Fedora'
