---
# - name: initial; get Name cloud attribute from meta-data
#   shell: curl -s --connect-timeout .1 http://169.254.169.254/0.1/meta-data/attributes/Name || true
#   register: cloud_Name

# - name: initial; set hostname invadelabs.com
#   command: hostname invadelabs.com
#   when: 'cloud_Name.stdout == "invadelabs.com"'

- name: initial; ensure "drew" is in sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^drew ALL='
    line: 'drew ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: initial; mkdir /root/installers
  file:
    path: /root/installers
    state: directory

#XXX install python2-libselinux here
- name: initial; add /etc/motd
  template:
    src: templates/etc/motd.j2
    dest: /etc/motd

- name: initial; stat /etc/localtime
  stat: path=/etc/localtime
  register: tz_localtime
# - debug:
#     msg: "{{ tz_localtime.stat.lnk_target }}"

- name: initial; set timezone
  command: timedatectl set-timezone America/Denver
  when: tz_localtime.stat.lnk_target != "../usr/share/zoneinfo/America/Denver"

# will be handled by gce firewall list
- name: initial; disable sshguard invadelabs.com
  service: name=sshguard state=stopped enabled=no
  when: ansible_fqdn == "invadelabs.com"

- name: initial; drew-piv3; apt; install fail2ban
  apt: name=fail2ban state=present
  when: ansible_hostname == "drew-piv3"

- name: initial; apt; install etckeeper and initial packages
  apt:
    pkg:
    - etckeeper
    - python-apt # for ansible
    state: present
  when: ansible_os_family == "Debian"

- name: initial; dnf; install etckeeper # XXX fix python2-dnf requirement for fedora 30
  dnf: name=etckeeper state=present
  when: ansible_distribution == "Fedora"

- name: initial; gitconfig
  git_config:
    name: "{{git_item.key}}"
    scope: global
    value: "{{git_item.value}}"
  with_dict: {
    "user.email": "drew@invadelabs.com",
    "user.name": "Drew Holt"
    }
  loop_control:
    loop_var: git_item

- name: initial; set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive
  when: ansible_distribution == 'Fedora'

- name: initial; add .forward
  copy:
    dest: "{{forward_item.value}}/.forward"
    owner: "{{forward_item.key}}"
    group: "{{forward_item.key}}"
    content: "drewderivative@gmail.com"
  with_dict: {
    "drew": "/home/drew",
    "root": "/root"
    }
  loop_control:
    loop_var: forward_item

- name: initial; git clone --depth 1 invadelabs.com/cron-invadelabs
  git:
    repo: https://github.com/invadelabs/cron-invadelabs.git
    dest: /root/scripts
    depth: 1

- name: initial; nrpe; dl check_memory.pl
  get_url:
    url: https://gist.githubusercontent.com/drew-holt/4da247a2874b7a0470bd3d55d5191312/raw/d24673b607dfee98f8a859acca21ef5dde26aa3d/check_memory.pl
    dest: /usr/local/bin/check_memory.pl
    mode: 0755
    force: no
    checksum: "sha256:2269ac81e514a3c75dec030c5dc8d3a058729755c6cbca250e69f717a1ac7978"
  when: ( ansible_host == "drew-serv" ) or ( ansible_host == "drew-pine64" )

# dl check_fail2ban.sh http://nagios.fm4dd.com/plugins/manual/check_fail2ban.htm
- name: initial; nrpe; dl fail2ban.sh
  get_url:
    url: http://nagios.fm4dd.com/plugins/source/check_fail2ban.sh
    dest: /usr/lib/nagios/plugins/check_fail2ban.sh
    mode: 0755
    force: no
    checksum: "sha256:bd5f071f253c27ae18ae5f7dd984d7ac31ac2962f24be84bcbee5395aea5f578"
  when: ansible_host == "drew-piv3"

## slacktee.sh
- name: initial; ansi2html.sh
  get_url:
    url: https://raw.githubusercontent.com/pixelb/scripts/dce7689196f6fd2efa87fd2d64e6e491c927b349/scripts/ansi2html.sh
    dest: /usr/local/bin/ansi2html.sh
    mode: 0755
    force: no
    checksum: "sha256:6bff734f83234046cb94de6bff001f0038104462c5336769f09b6f0df9cc6d2e"

## slacktee.sh
- name: initial; slacktee.sh
  get_url:
    url: https://raw.githubusercontent.com/coursehero/slacktee/v1.4.2/slacktee.sh
    dest: /usr/local/bin/slacktee.sh
    mode: 0755
    force: no
    checksum: "sha256:f17b39737c5fe1926c354890ac6e9e5cf11afd09d8351e9b498fe9a608cf2e95"

- name: initial; nrpe; download check_temp.sh
  copy:
    src: /root/scripts/check_temp.sh
    dest: /usr/local/bin/check_temp.sh
    mode: 0755
    remote_src: yes

- name: initial; nrpe; /var/run/fail2ban/fail2ban.sock perms
  file:
    dest: /var/run/fail2ban/fail2ban.sock
    owner: root
    group: nagios
    mode: 0770
  when: ansible_host == "drew-piv3"
