---
  - name: initial; set hostname
    command: hostname invadelabs.com
    when: (ansible_fqdn != "invadelabs.com")

  - name: initial; Install initial packages
    apt: name={{item}} state=present # update_cache=yes
    with_items:
    - etckeeper
    - python-apt # for ansible
    # - fail2ban # sshguard in ubuntu 18.04

  - name: initial; gitconfig
    git_config:
      name: "{{item.key}}"
      scope: global
      value: "{{item.value}}"
    with_dict: {
      'user.email': 'drew@invadelabs.com',
      'user.name': 'Drew Holt'
      }

  - name: initial; Initalize etckeeper
    shell: |
      etckeeper init
      etckeeper post-install
    args:
      chdir: /etc
      creates: /etc/.git
