---
# this passes to filebeat.yml in next step
- name: logging; get home_ip contents and set to var
  ansible.builtin.slurp:
    src: /home/drew/home_ip
  when: ansible_fqdn == "invadelabs.com"
  register: home_ip

- name: logging; add /etc/filebeat/filebeat.yml
  template:
    src: templates/etc/filebeat/filebeat-{{ ansible_fqdn }}.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600
    validate: "filebeat test config -c %s"
  when: ( ansible_fqdn == "invadelabs.com" ) or ( ansible_host == "drew-serv" )
  notify: Restart filebeat.service

- name: logging; /etc/systemd/journald.conf
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^{{ journald_item.key }}"
    line: "{{ journald_item.key }}={{ journald_item.value }}"
    state: present
  with_dict: {
    "ForwardToSyslog": "yes"
  }
  loop_control:
    loop_var: journald_item
  notify: Restart systemd-journald.service

- name: logging; add /etc/sysctl.d/vm.max_map_count.conf drew-serv # for logstash container
  copy:
    dest: "/etc/sysctl.d/vm.max_map_count.conf"
    content: "vm.max_map_count = 262144"
    owner: root
    group: root
    mode: 0600
  when: ansible_host == "drew-serv"
  notify: Restart rsyslog.service

- name: logging; add /etc/rsyslog.d entries
  template:
    src: "templates/etc/rsyslog.d/{{ rsyslog_item }}.j2"
    dest: "/etc/rsyslog.d/{{ rsyslog_item }}"
    owner: root
    group: root
    mode: 0644
    # doesn't work due to require %s to verify individual config
    # validate: 'rsyslogd -N1 -f /etc/rsyslog.conf'
  with_items:
    - logstash.conf
    - ignore-audit.conf
    - ignore-rngd.conf
    - ignore-systemd.conf
    - ignore-sudo.conf
    - ignore-cron.conf
    - ignore-sshd.conf
  loop_control:
    loop_var: rsyslog_item
  notify: Restart rsyslog.service

- name: logging; remove logwatch daily
  file:
    path: '{{ logwatch_item }}'
    state: absent
  with_items:
    - /etc/cron.daily/00logwatch
    - /etc/cron.daily/0logwatch
  loop_control:
    loop_var: logwatch_item

- name: logging; add /etc/logwatch/conf/logwatch.conf
  template:
    src: templates/etc/logwatch/conf/logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
    owner: root
    group: root
    mode: 0644
