---
# nginx config
- name: nginx; add site templates
  template:
    src: templates/etc/nginx/{{nginx_template_item}}.conf.j2
    dest: /srv/nginx/{{nginx_template_item}}.conf
  with_items:
    - nginx
    - ssl-inv-default
    - conf.d/default
    - conf.d/cgm.invadelabs.com
    - conf.d/drew.invadelabs.com
  loop_control:
    loop_var: nginx_template_item
  notify: docker; reload nginx
