---
- name: nrpe; nrpe.cfg
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: "^{{nrpecfg_item.key}}="
    line: "{{nrpecfg_item.key}}={{nrpecfg_item.value}}"
    state: present
  with_dict: {
    "allowed_hosts": "{{nrpe_allowed_hosts}}",
    "include": "/etc/nagios/nrpe_local.cfg"
    }
  loop_control:
    loop_var: nrpecfg_item
  notify:
    - Restart nrpe.service
    - Restart nagios-nrpe-server.service

- name: nrpe; nrpe_local.cfg
  lineinfile:
    dest: "/etc/nagios/nrpe_local.cfg"
    regexp: "^command\\[{{nrpe_spec_item.key}}\\]"
    line: "command[{{nrpe_spec_item.key}}]={{nrpe_spec_item.value}}"
    state: present
  with_dict: "{{ nrpe_all + nrpe_specific }}" # see host_vars/host.yml or groups_vars/group.yml
  loop_control:
    loop_var: nrpe_spec_item
  vars:
    nrpe_all:
      - "check_users": "{{nrpe_plugins_dir}}/check_users -w 5 -c 10"
      - "check_mailq": "{{nrpe_plugins_dir}}/check_mailq -w 1 -c 2"
  notify:
    - Restart nrpe.service
    - Restart nagios-nrpe-server.service

# pine64 buster needs something like
# libb-hooks-op-check-perl
# libclass-accessor-perl
# libconfig-tiny-perl
# libdevel-callchecker-perl
# libdynaloader-functions-perl
# libmath-calc-units-perl
# libmodule-implementation-perl
# libmodule-runtime-perl
# libparams-classify-perl
# libparams-validate-perl
# libsub-name-perl
# libtry-tiny-perl
# dpkg -i http://ftp.us.debian.org/debian/pool/main/libn/libnagios-plugin-perl/libnagios-plugin-perl_0.36-1_all.deb
