---
- name: nrpe; nrpe.cfg
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: "^{{nrpecfg_item.key}}="
    line: "{{nrpecfg_item.key}}={{nrpecfg_item.value}}"
    state: present
  with_dict: {
    "allowed_hosts": "{{nrpe_allowed_hosts}}",
    "include": "/etc/nagios/nrpe_local.cfg"
    }
  loop_control:
    loop_var: nrpecfg_item
  notify:
    - Restart nrpe.service
    - Restart nagios-nrpe-server.service

- name: nrpe; nrpe_local.cfg generic
  lineinfile:
    dest: "/etc/nagios/nrpe_local.cfg"
    regexp: "^command\\[{{nrpe_gen_item.key}}\\]"
    line: "command[{{nrpe_gen_item.key}}]={{nrpe_gen_item.value}}"
    create: yes
    state: present
  with_dict: {
    "check_users": "{{nrpe_plugins_dir}}/check_users -w 5 -c 10",
    "check_zombie_procs": "{{nrpe_plugins_dir}}/check_procs -w 5 -c 10 -s Z",
    "check_mailq": "{{nrpe_plugins_dir}}/check_mailq -w 1 -c 2",
    "check_temp": "/usr/local/bin/check_temp.sh -d /sys/class/thermal/thermal_zone0/temp -w 60 -c 65",
    }
  loop_control:
    loop_var: nrpe_gen_item
  notify:
    - Restart nrpe.service
    - Restart nagios-nrpe-server.service

- name: nrpe; nrpe_local.cfg host specific
  lineinfile:
    dest: "/etc/nagios/nrpe_local.cfg"
    regexp: "^command\\[{{nrpe_spec_item.key}}\\]"
    line: "command[{{nrpe_spec_item.key}}]={{nrpe_spec_item.value}}"
    state: present
  with_dict: "{{ nrpe_specific }}"
  loop_control:
    loop_var: nrpe_spec_item
  notify:
    - Restart nrpe.service
    - Restart nagios-nrpe-server.service
