---
- name: nrpe; nrpe.cfg allowed_hosts=192.168.1.0/24,172.17.0.0/16,127.0.0.1,::1
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: "^allowed_hosts="
    line: "allowed_hosts=192.168.1.0/24,172.17.0.0/16,127.0.0.1,::1"
    state: present
  notify:
    - Restart nrpe.service
    - Restart nagios-nrpe-server.service
  when: 'ansible_default_ipv4.network == "192.168.1.0"'

# for drew-serv.invadelabs.com at the moment
- name: nrpe; drew-serv add /etc/nrpe.d/nrpe_local.cfg template
  template:
    src: templates/etc/nrpe.d/nrpe_local.cfg.j2
    dest: /etc/nrpe.d/nrpe_local.cfg
  notify: Restart nrpe.service
  when: ansible_fqdn == "drew-serv.invadelabs.com"

- name: nrpe; dl check_memory.pl
  get_url:
    url: https://gist.githubusercontent.com/drew-holt/4da247a2874b7a0470bd3d55d5191312/raw/d24673b607dfee98f8a859acca21ef5dde26aa3d/check_memory.pl
    dest: /usr/local/bin/check_memory.pl
    mode: 0755
    force: no
    checksum: "sha256:2269ac81e514a3c75dec030c5dc8d3a058729755c6cbca250e69f717a1ac7978"
  when: ansible_fqdn == "drew-pine64.invadelabs.com"

- name: nrpe; download check_temp.sh
  copy:
    src: /root/scripts/check_temp.sh
    dest: /usr/local/bin/check_temp.sh
    mode: 0755
    remote_src: yes

- name: nrpe; /etc/nagios/nrpe_local.cfg
  lineinfile:
    dest: /etc/nagios/nrpe_local.cfg
    regexp: "^command\\[{{nrpe_item.key}}\\]"
    line: "command[{{nrpe_item.key}}]={{nrpe_item.value}}"
    state: present
  with_dict: {
    "check_users": "/usr/lib/nagios/plugins/check_users -w 5 -c 10",
    "check_load": "/usr/lib/nagios/plugins/check_load -r -w 4,2,1 -c 6,4,2",
    "check_zombie_procs": "/usr/lib/nagios/plugins/check_procs -w 5 -c 10 -s Z",
    "check_total_procs": "/usr/lib/nagios/plugins/check_procs -w 200 -c 250",
    "check_apt": "/usr/lib/nagios/plugins/check_apt -t 60",
    "check_mailq": "/usr/lib/nagios/plugins/check_mailq -w 1 -c 2",
    "check_uptime": "/usr/lib/nagios/plugins/check_uptime -f -c 10",
    "check_temp": "/usr/local/bin/check_temp.sh -d /sys/class/thermal/thermal_zone0/temp -w 60 -c 65",
    "check_memory": "{{ check_memory }}",
    "check_root": "{{ check_root }}"
    }
  loop_control:
    loop_var: nrpe_item
  notify: Restart nagios-nrpe-server.service
  when: ansible_os_family == "Debian"

# drew-pine64 uses /dev/root /dev/mmcblk0p2
- name: nrpe; invadelabs.com; nrpe_local.cfg; check_tcp11514
  lineinfile:
    dest: /etc/nagios/nrpe_local.cfg
    regexp: "^command\\[check_tcp11514\\]"
    line: "command[check_tcp11514]=/usr/lib/nagios/plugins/check_tcp -H localhost -p 11514"
    state: present
  notify: Restart nagios-nrpe-server.service
  when: ansible_fqdn == "invadelabs.com"

# dl check_fail2ban.sh http://nagios.fm4dd.com/plugins/manual/check_fail2ban.htm
- name: nrpe; add fail2ban.sh
  get_url:
    url: http://nagios.fm4dd.com/plugins/source/check_fail2ban.sh
    dest: /usr/lib/nagios/plugins/check_fail2ban.sh
    mode: 0755
    force: no
    checksum: "sha256:bd5f071f253c27ae18ae5f7dd984d7ac31ac2962f24be84bcbee5395aea5f578"
  when: ansible_fqdn == "drew-piv3.invadelabs.com"

- name: nrpe; /var/run/fail2ban/fail2ban.sock perms
  file:
    dest: /var/run/fail2ban/fail2ban.sock
    owner: root
    group: nagios
    mode: 0770
  when: ansible_fqdn == "drew-piv3.invadelabs.com"

# drew-piv3 add fail2ban check
- name: nrpe; drew-piv3; nrpe_local.cfg; check_fail2ban
  lineinfile:
    dest: /etc/nagios/nrpe_local.cfg
    regexp: "^command\\[check_fail2ban\\]"
    line: "command[check_fail2ban]=/usr/lib/nagios/plugins/check_fail2ban.sh -w 1 -c 2"
    state: present
  notify: Restart nagios-nrpe-server.service
  when: ansible_fqdn == "drew-piv3.invadelabs.com"
