---
- name: nrpe.cfg allowed_hosts=192.168.1.0/24,172.17.0.0/16,127.0.0.1,::1
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: "^allowed_hosts="
    line: "allowed_hosts=192.168.1.0/24,172.17.0.0/16,127.0.0.1,::1"
    state: present
  notify: Restart nrpe.service

- name: Add /etc/nrpe.d/nrpe_local.cfg template
  template:
    src: templates/etc/nrpe.d/nrpe_local.cfg.j2
    dest: /etc/nrpe.d/nrpe_local.cfg
  notify: Restart nrpe.service
