---
- name: nrpe; nrpe.cfg allowed_hosts=192.168.1.0/24,172.17.0.0/16,127.0.0.1,::1
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: "^allowed_hosts="
    line: "allowed_hosts=192.168.1.0/24,172.17.0.0/16,127.0.0.1,::1"
    state: present
  notify:
    - Restart nrpe.service
    - Restart nagios-nrpe-server.service
  when: 'ansible_default_ipv4.network == "192.168.1.0"'

# for drew-serv.invadelabs.com at the moment
- name: nrpe; add /etc/nrpe.d/nrpe_local.cfg template
  template:
    src: templates/etc/nrpe.d/nrpe_local.cfg.j2
    dest: /etc/nrpe.d/nrpe_local.cfg
  notify: Restart nrpe.service
  when: ansible_distribution == "Fedora"
  # XXX better bounds checking, fedora / debian use diff nrpe default config location though

# for check_memory.pl
- name: nrpe; apt_key; add jessie-backports
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7638D0442B90D010
  when: (ansible_fqdn == "drew-piv3.invadelabs.com") or (ansible_fqdn == "drew-pine64.invadelabs.com")

- name: nrpe; apt_repository; add jessie-backports
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
    state: present
  when: (ansible_fqdn == "drew-piv3.invadelabs.com") or (ansible_fqdn == "drew-pine64.invadelabs.com")

- name: nrpe; apt; install libmonitoring-plugin-perl
  apt:
    name: libmonitoring-plugin-perl
    state: present
    default_release: jessie-backports
    install_recommends: no
    #update_cache: yes
  when: (ansible_fqdn == "drew-piv3.invadelabs.com") or (ansible_fqdn == "drew-pine64.invadelabs.com")

- name: nrpe; dl check_memory.pl
  get_url:
    url: https://gist.githubusercontent.com/drew-holt/4da247a2874b7a0470bd3d55d5191312/raw/d24673b607dfee98f8a859acca21ef5dde26aa3d/check_memory.pl
    dest: /usr/local/bin/check_memory.pl
    mode: 0755
    force: no

- name: nrpe; download check_temp.sh
  get_url:
    url: https://raw.githubusercontent.com/invadelabs/cron-invadelabs/master/check_temp.sh
    dest: /usr/local/bin/check_temp.sh
    mode: 0755
    force: no

- name: nrpe; /etc/nagios/nrpe_local.cfg
  lineinfile:
    dest: /etc/nagios/nrpe_local.cfg
    regexp: "^command\\[{{item.key}}\\]"
    line: "command[{{item.key}}]={{item.value}}"
    state: present
  with_dict: {
    "check_users": "/usr/lib/nagios/plugins/check_users -w 5 -c 10",
    "check_load": "/usr/lib/nagios/plugins/check_load -r -w 4,2,1 -c 6,4,2",
    "check_zombie_procs": "/usr/lib/nagios/plugins/check_procs -w 5 -c 10 -s Z",
    "check_total_procs": "/usr/lib/nagios/plugins/check_procs -w 200 -c 250",
    "check_apt": "/usr/lib/nagios/plugins/check_apt -t 60",
    "check_mailq": "/usr/lib/nagios/plugins/check_mailq -w 1 -c 2",
    "check_uptime": "/usr/lib/nagios/plugins/check_uptime -f -c 10",
    "check_temp": "/usr/local/bin/check_temp.sh -d /sys/class/thermal/thermal_zone0/temp -w 60 -c 65",
    "check_memory": "/usr/local/bin/check_memory.pl -u M -w 10% -c 20%"
    }
  notify: Restart nagios-nrpe-server.service
  when: (ansible_fqdn == "drew-piv3.invadelabs.com") or (ansible_fqdn == "drew-pine64.invadelabs.com")

# drew-piv3 uses /dev/root /dev/mmcblk0p2
- name: nrpe; drew-piv3; nrpe_local.cfg; check_sda1
  lineinfile:
    dest: /etc/nagios/nrpe_local.cfg
    regexp: "^command\\[check_sda1\\]"
    line: "command[check_sda1]=/usr/lib/nagios/plugins/check_disk -c 10% -p /dev/mmcblk0p2"
    state: present
  notify: Restart nagios-nrpe-server.service
  when: ansible_fqdn == "drew-piv3.invadelabs.com"

# drew-pine64 uses /dev/root /dev/mmcblk0p2
- name: nrpe; drew-pine64; nrpe_local.cfg; check_sda1
  lineinfile:
    dest: /etc/nagios/nrpe_local.cfg
    regexp: "^command\\[check_sda1\\]"
    line: "command[check_sda1]=/usr/lib/nagios/plugins/check_disk -c 10% -p /dev/mmcblk0p1"
    state: present
  notify: Restart nagios-nrpe-server.service
  when: ansible_fqdn == "drew-pine64.invadelabs.com"

# dl check_fail2ban.sh http://nagios.fm4dd.com/plugins/manual/check_fail2ban.htm
- name: nrpe; add fail2ban.sh
  get_url:
    url: http://nagios.fm4dd.com/plugins/source/check_fail2ban.sh
    dest: /usr/lib/nagios/plugins/check_fail2ban.sh
    mode: 0755
    force: no
  when: ansible_fqdn == "drew-piv3.invadelabs.com"

- name: nrpe; /var/run/fail2ban/fail2ban.sock perms
  file:
    dest: /var/run/fail2ban/fail2ban.sock
    owner: root
    group: nagios
    mode: 0770
  when: ansible_fqdn == "drew-piv3.invadelabs.com"

# drew-piv3 add fail2ban check
- name: nrpe; drew-piv3; nrpe_local.cfg; check_fail2ban
  lineinfile:
    dest: /etc/nagios/nrpe_local.cfg
    regexp: "^command\\[check_fail2ban\\]"
    line: "command[check_fail2ban]=/usr/lib/nagios/plugins/check_fail2ban.sh -w 1 -c 2"
    state: present
  notify: Restart Restart nagios-nrpe-server.service
  when: ansible_fqdn == "drew-piv3.invadelabs.com"
