---
- name: ntop; ntopng config
  lineinfile:
    dest: /etc/ntopng/ntopng.conf
    regexp: "^{{ ntop_item.key }}"
    line: "{{ ntop_item.key }}"
    state: present
  with_dict: {
    '-n=1': '',
    '-q': '',
    '-i=eth0': '',
    '-m=192.168.1.0/24': '',
    '-S=local': ''
  }
  loop_control:
    loop_var: ntop_item
  notify:
    - Restart ntopng.service
