---
- name: nut_ups; udev rules
  template:
    src: templates/etc/udev/rules.d/50-ups.rules.j2
    dest: /etc/udev/rules.d/50-ups.rules.j2
    owner: root
    group: root
    mode: "0644"

- name: nut_ups; configs
  template:
    src: templates/etc/ups/{{nut_item.key}}.j2
    dest: /etc/ups/{{nut_item.key}}
    owner: root
    group: nut
    mode: "{{nut_item.value}}"
  with_dict: {
    'hosts.conf': '0644',
    'notifycmd.sh': '0755',
    'nut.conf': '0640',
    'ups.conf': '0640',
    'upsd.users': '0640',
    'upsmon.conf': '0640',
    'upsd.conf': '0640'
    }
  loop_control:
    loop_var: nut_item
  notify:
    - Restart nut-server.service
    - Restart nut-monitor.service