- name: pihole; add pihole custom.list
  template:
    src: "templates/srv/pihole/etc-pihole/custom.list.j2"
    dest: "/srv/pihole/etc-pihole/custom.list.j2"
    owner: drew
    group: drew
    mode: 0644
  when: "'pihole' in group_names"
  notify: docker; reload pihole custom.list and flush cache