---
## pine 64 requirements
- name: pip; pip upgrade to 10.0.1
  pip:
    name: pip
    version: 10.0.1
  when: ansible_host == "drew-pine64"

- name: pip; pine64 extras needed for pip
  apt:
    pkg:
      - libmonitoring-plugin-perl # for nrpe
      - python-dev # needed to build ansible via pip on pine64 u16.04
      - libffi-dev # needed to build ansible via pip on pine64 u16.04
      - python-pkg-resources # needed to build ansible via pip on pine64 u16.04
    state: present
  when: ansible_host == "drew-pine64"

## pip for ARM
- name: pip; install ansible via pip on arm
  pip:
    name: ansible
  when: ( ansible_host == "drew-pine64" ) or ( ansible_host == "drew-piv3" ) or ( 'rpi-cluster' in group_names )

## docker
- name: pip; install pip modules for docker
  pip:
    name:
    - setuptools
    - docker-py # needed for ubuntu16.04-armhf ansible & docker-py
  when: ( ansible_host == "drew-pine64" ) or ( ansible_host == "drew-piv3" ) or ( 'rpi-cluster' in group_names )
