---
- name: pip; install check-docker on drew-serv
  pip:
    name:
      - check-docker
      - pymongo
  when: ansible_host == "drew-serv"

- name: pip; install check-docker on drew-pine64
  pip:
    name:
      - docker-py
  when: ansible_host == "drew-pine64"
