---
- name: pkgs_debian; pip upgrade to 10.0.1
  pip:
    name: pip
    version: 10.0.1
  when: ansible_fqdn == "drew-pine64.invadelabs.com"

- name: pkgs_debian; install pip modules for docker # needed for ubuntu16.04-armhf ansible & docker-py
  pip:
    name: "{{docker_pip_item}}"
  with_items:
  - setuptools
  - docker-py
  loop_control:
    loop_var: docker_pip_item
