---
- name: pkgs_fedora; install base packages
  dnf:
    state: present
    name:
    - docker # docker-ce when fedora 28 stable pkgs are available
    - docker-compose
    # base bits
    - ansible
    - autossh
    - rsync
    - jq
    - redhat-lsb-core
    - vim-enhanced
    - mcelog
    - logwatch
    - cronie # crontab
    - git # for github.com/invadelabs/cron-invadelabs
    - bc # for github.com/invadelabs/cron-invadelabs
    - bind-utils # for dig
    - dnf-plugins-core # for docker install
    - snapd # for drive
    - pxz # parallel xz for backups
    - wget
    - chrony
    - samba
    - httpd
    - mod_ssl
    - postfix
    - cyrus-sasl-plain # needed for sendmail + postfix
    - rsyslog # for elasticsearch
    - mailx
    - screen
    - smartmontools
    - lm_sensors
    - lynis
    # python bits
    - python2-pip # for ansible docker module
    - python2-virtualenv # for ansible docker module
    - libselinux-python # for ansible
    # nagios / nrpe bits
    - nrpe
    - nagios-plugins-nrpe
    - nagios-plugins-users
    - nagios-plugins-load
    - nagios-plugins-disk
    - nagios-plugins-procs
    - nagios-plugins-check-updates
    - nagios-plugins-mailq
    - nagios-plugins-uptime
    - perl-Nagios-Plugin
    - perl-Monitoring-Plugin
    # hypervisor
    - qemu-kvm
    - libvirt
    - virt-install
    - bridge-utils
    - libguestfs-tools
  notify: # XXX break this into smaller groups for when new packages are needed
  - Start docker.service
  - Start chronyd.service
  - Start mcelog.service
  - Start smb.service
  - Start nmb.service
  - Start httpd.service
  - Start postfix.service
  - Start rsyslog.service
  - Start nrpe.service
  - Start libvirtd.service
  - Setup lm_sensors

## filebeat
- name: pkgs_fedora; download filebeat rpm
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.2.4-x86_64.rpm
    dest: /root/installers/filebeat-6.2.4-x86_64.rpm
    force: no
    checksum: "sha256:479a25895ac022afaa44f6e15ae6eb396fa7db03f7e4c05b14c5d6fb21b6815d"

- name: pkgs_fedora; install filebeat rpm
  dnf:
    name: /root/installers/filebeat-6.2.4-x86_64.rpm
  when: ansible_os_family == "RedHat"
  notify: Start filebeat.service

# ## rclone
# - name: pkgs_fedora; download rclone rpm
#   get_url:
#     url: https://downloads.rclone.org/v1.41/rclone-v1.41-linux-amd64.rpm
#     dest: /root/installers/rclone-v1.41-linux-amd64.rpm
#     force: no
#     checksum: "sha256:8f43108e81ee2652c2f66fc3a260e111b018daba9162898e2d6c38220cc8b72a"
#
# - name: pkgs_fedora; install rclone rpm
#   dnf:
#     name: /root/installers/rclone-v1.41-linux-amd64.rpm

- name: pkgs_fedora; install google-cloud-sdk snap
  command: snap install google-cloud-sdk --classic
