---
- name: pkgs_fedora; install base packages
  dnf:
    state: present
    name:
    # https://www.linuxuprising.com/2019/11/how-to-install-and-use-docker-on-fedora.html
    # XXX switch moby-engine for podman at some point
    # sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
    - moby-engine # replaces upstream docker package in fedora 31
    - docker-compose
    - grubby
    # base bits
    - ansible
    - autossh
    - rsync
    - jq
    - redhat-lsb-core # XXX used for which script?
    - vim-enhanced
    - mcelog
    - logwatch
    - rclone # googledrive cli backup
    - cronie # crontab
    - git # for github.com/invadelabs/cron-invadelabs
    - bc # for github.com/invadelabs/cron-invadelabs
    - bind-utils # for dig
    - dnf-plugins-core # for moby-engine / docker-ce install
    - snapd # for google-cloud-sdk
    - pxz # parallel xz for backups
    - wget
    - chrony
    - samba
    - httpd
    - mod_ssl
    - mod_http2
    - postfix
    - cyrus-sasl-plain # needed for postfix + sendgrid
    - rsyslog # for elasticsearch
    - mailx
    - screen
    - smartmontools
    - lm_sensors
    - lynis
    - fuse-encfs
    - powertop
    - upower # /etc/UPower/Upower.conf
    # nagios / nrpe bits
    - nrpe
    - nagios-plugins-nrpe
    - nagios-plugins-users
    - nagios-plugins-load
    - nagios-plugins-disk
    - nagios-plugins-procs
    - nagios-plugins-check-updates
    - nagios-plugins-mailq
    - nagios-plugins-uptime
    - perl-Nagios-Plugin
    - perl-Monitoring-Plugin
    # # hypervisor
    # - qemu-kvm
    # - libvirt
    # - virt-install
    # - libguestfs-tools
    - bridge-utils

    # sec
    - chkrootkit
    - needrestart
  notify: # XXX break this into smaller groups for when new packages are needed
  - Start chronyd.service
  - Start docker.service
  - Start httpd.service
  - Start mcelog.service
  - Start powertop.service
  - Start postfix.service
  - Start nmb.service
  - Start nrpe.service
  - Start rsyslog.service
  - Start smb.service
  # - Start libvirtd.service
  - Setup lm_sensors

## filebeat
- name: pkgs_fedora; download filebeat rpm
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.2.4-x86_64.rpm
    dest: /root/installers/filebeat-6.2.4-x86_64.rpm
    force: no
    checksum: "sha256:479a25895ac022afaa44f6e15ae6eb396fa7db03f7e4c05b14c5d6fb21b6815d"

- name: pkgs_fedora; install filebeat rpm
  dnf:
    name: /root/installers/filebeat-6.2.4-x86_64.rpm
  when: ansible_os_family == "RedHat"
  notify: Start filebeat.service

# google cloud sdk
- name: pkgs_fedora; install google-cloud-sdk snap
  command: snap install google-cloud-sdk --classic
  args:
    creates: /var/lib/snapd/snap/bin/gcloud

- debug:
    msg: "Run `gcloud auth login drewderivative@gmail.com` if we fail here"

- name: pkgs_fedora; if google cloud sdk initalized
  shell: gcloud auth list | grep drewderivative@gmail.com && touch /var/log/gcloud-sdk.touch
  args:
    chdir: /root
    creates: /var/log/gcloud-sdk.touch
  register: rclone_stat
  failed_when: rclone_stat.rc != 0 # rc = proccess exit code
  when: ansible_host == "drew-serv"

- debug:
    msg: "Run `gcloud config set project invadelabs` if we fail here"

- name: pkgs_fedora; if google cloud sdk project set
  shell: gcloud config list project | grep invadelabs && touch /var/log/gcloud-sdk-proj.touch
  args:
    chdir: /root
    creates: /var/log/gcloud-sdk.touch
  register: rclone_stat
  failed_when: rclone_stat.rc != 0 # rc = proccess exit code
  when: ansible_host == "drew-serv"
