---
## debconf
- name: pkgs_debian; debconf; postfix; option type 'Internet with smarthost'
  debconf: name=postfix question="postfix/main_mailer_type" value="'Internet with smarthost'" vtype="string"

- name: pkgs_debian; debconf; postfix; option type 'System mail name'
  debconf: name=postifx question="postfix/mailname" value="invadelabs.com" vtype="string"

## base packages to install on every device
- name: pkgs_debian; install packages
  apt:
    pkg:
    - mailutils
    - postfix
    - libsasl2-modules # needed for postfix sendgrid

    #- libnagios-plugin-perl # XXX needed for nagios-plugins-contrib (deps broken?) / broken on invadelabs.com
    - monitoring-plugins-standard
    - nagios-nrpe-server
    - monitoring-plugins-basic
    - nagios-plugins-contrib # XXX installs a lo tof deps for 1 scripts, work around?
    - debian-keyring # needed for nrpe debian package
    - debian-archive-keyring # needed for nrpe debian package

    #- ansible # will be installed via pip for arm devices
    - software-properties-common # for ansible
    - python-paramiko # for ansible-pull
    - python-jinja2 # for ansible-pull

    - vim
    - logwatch
    - python-pip # needed for docker-py
    - libdate-manip-perl # needed for logwatch date ranges
    - curl # for invadelabs/cron-invadelabs
    - highlight # for invadelabs/cron-invadelabs
    - lynis # for invadelabs/cron-invadelabs/check_lynis.sh
    - bc # for invadelabs/cron-invadelabs/wiki_to_md.sh
    - pandoc # for invadelabs/cron-invadelabs/wiki_to_md.sh
    - pxz # for invadelabs/cron-invadelabs/gdrive.sh
    - gawk # for lynis and ansi2html
    - dbus # for lynis and ansi2html
    - jq
    state: present
  notify:
  - Start postfix.service
  - update-alternatives; editor vim-basic

## docker apt
- name: pkgs_debian; add docker key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present
  when: "'rpi-cluster' in group_names"

- name: pkgs_debian; apt repo docker-ce
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch edge
    state: present
  when: "'rpi-cluster' in group_names"

## kubernetes apt
- name: pkgs_debian; add kubernetes key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  when: "'rpi-cluster' in group_names"

- name: pkgs_debian; apt repo kubernetes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  when: "'rpi-cluster' in group_names"

## rpi-cluster apt docker-ce & kubenetes
- name: pkgs_debian; rpi-cluster docker and kubernetes
  apt:
    pkg:
      - docker-ce
      - kubeadm
    state: present
  when: "'rpi-cluster' in group_names"

## ntop
- name: pkgs_debian; add ntop apt key
  apt_key:
    url: http://packages.ntop.org/apt/ntop.key
    state: present
  when: ansible_host == "drew-piv3"

- name: pkgs_debian; apt repo ntop armhf
  apt_repository:
    repo: deb http://apt.ntop.org/stretch_pi armhf/
    state: present
  when: ansible_host == "drew-piv3"

- name: pkgs_debian; apt repo ntop all
  apt_repository:
    repo: deb http://apt.ntop.org/stretch_pi all/
    state: present
  when: ansible_host == "drew-piv3"

## install ntopng AND nut for ups
- name: pkgs_debian; drew-piv3 NUT for UPS
  apt:
    pkg:
      - ntopng
      - nut
      - nut-client
      - nut-server
    state: present
  when: ansible_host == "drew-piv3"
  notify:
    - Start ntopng.service
    - Start nut-driver.service
    - Start nut-server.service
    - Start nut-monitor.service

## invadelabs.com requirements
- name: pkgs_debian; invadelabs.com
  apt:
    pkg:
      - snapd # for invadelabs/cron-invadelabs/gdrive.sh
      - ansible

      - apache2
      - php7.2-fpm
      - libapache2-mod-php
      - php-sqlite3
      - php-mbstring
      - php-xml
      - php-curl
      - php-apcu

      - php-mbstring # for drewwiki

      - certbot
      - python-certbot-apache
    state: present
  notify:
  - Start apache2.service
  - Start php7.2-fpm.service
  when: ansible_fqdn == "invadelabs.com"

## mod_pagespeed
- name: pkgs_debian; download mod_pagespeed
  get_url:
    url: https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_amd64.deb
    dest: /root/installers/mod-pagespeed-stable_current_amd64.deb
    force: no
    checksum: "sha256:14de0b868f4da98bdfdf9cd8e2c12e3abc2a93029168ea27bfb3eb5ea158e3a5"
  when: ansible_fqdn == "invadelabs.com"

- name: pkgs_debian; install mod_pagespeed
  apt:
    deb: /root/installers/mod-pagespeed-stable_current_amd64.deb
  when: ansible_fqdn == "invadelabs.com"

## lynis
- name: pkgs_debian; download lynis
  get_url:
    url: http://ftp.debian.org/debian/pool/main/l/lynis/lynis_2.6.2-1_all.deb
    dest: /root/installers/lynis_2.6.2-1_all.deb
    force: no
    checksum: "sha256:7a9d0b3f20cd21599272d0525dc0c37807b7c62c39ed529107d47309e4ceff32"
  when: (ansible_host == "drew-piv3") or (ansible_host == "drew-pine64") or ( 'rpi-cluster' in group_names )

- name: pkgs_debian; install lynis
  apt:
    deb: /root/installers/lynis_2.6.2-1_all.deb
  when: (ansible_host == "drew-piv3") or (ansible_host == "drew-pine64") or ( 'rpi-cluster' in group_names )

## filebeat
- name: pkgs_debian; download filebeat deb
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.2.4-amd64.deb
    dest: /root/installers/filebeat-6.2.4-amd64.deb
    force: no
    checksum: "sha256:003c3a49450c30f3c92543226108a99dfaf70f8eca5869b30d0f31859a23e010"
  when: ansible_fqdn == "invadelabs.com"

- name: pkgs_debian; install filebeat deb
  apt:
    deb: /root/installers/filebeat-6.2.4-amd64.deb
  when: ansible_fqdn == "invadelabs.com"
  notify: Start filebeat.service

## rclone-1.48.0
- name: pkgs_debian; download filebeat deb
  get_url:
    url: https://downloads.rclone.org/v1.48.0/rclone-v1.48.0-linux-amd64.deb
    dest: /root/installers/rclone-v1.48.0-linux-amd64.deb
    force: no
    checksum: "sha256:e4b7a63ca6fa2bee37cbb33afeaa3fa60be2c595ef95a0b262ad8c8e770ea3b3"
  when: ansible_fqdn == "invadelabs.com"

- name: pkgs_debian; install rclone
  apt:
    deb: /root/installers/rclone-v1.48.0-linux-amd64.deb
  when: ansible_fqdn == "invadelabs.com"
