---
## debconf
- name: pkgs_debian; debconf; postfix; option type 'Internet with smarthost'
  debconf: name=postfix question="postfix/main_mailer_type" value="'Internet with smarthost'" vtype="string"

- name: pkgs_debian; debconf; postfix; option type 'System mail name'
  debconf: name=postifx question="postfix/mailname" value="invadelabs.com" vtype="string"

- name: pkgs_debian; debconf; debsescan; skip daily email
  debconf: name=postifx question="debsecan/report" value=false vtype="boolean"

## base packages to install on every device
- name: pkgs_debian; install packages
  apt:
    pkg:
    - mailutils
    - postfix
    - libsasl2-modules # needed for postfix + sendgrid
    # - python-apt # needed for rasbian buster ansible
    - python3-pip

    #- libnagios-plugin-perl # XXX needed for nagios-plugins-contrib (deps broken?) / broken on invadelabs.com
    - monitoring-plugins-standard
    - nagios-nrpe-server
    - monitoring-plugins-basic
    - nagios-plugins-contrib # XXX installs ~112 pkg deps for check_memory / check_uptime, work around?
    # - debian-keyring # needed for nrpe debian package
    # - debian-archive-keyring # needed for nrpe debian package
    - sysstat # for check_iostat

    - ansible

    - vim
    - logwatch
    - curl # for invadelabs/cron-invadelabs
    - highlight # for invadelabs/cron-invadelabs
    - lynis # for invadelabs/cron-invadelabs/check_lynis.sh
    - bc # for invadelabs/cron-invadelabs/wiki_to_md.sh
    - pandoc # for invadelabs/cron-invadelabs/wiki_to_md.sh
    - gawk # for lynis and ansi2html
    - dbus # for lynis and ansi2html
    - jq

    # sec
    - libpam-tmpdir # set $TMP and $TMPDIR for PAM sessions [CUST-0280]
    - debsums # for the verification of installed package files against MD5 checksums. [CUST-0875]
    - needrestart # after upgrades to determine which daemons are using old versions of libraries and need restarting. [CUST-0831]
    - chkrootkit # malware scanner, to perform periodic file system scans [HRDN-7230]
    state: present
  notify:
  - Start postfix.service
  - update-alternatives; editor vim-basic

#
- name: pkgs_debian; install unclutter
  apt:
    pkg:
      - unclutter
      - synergy
    state: present
  when: ansible_host == "drew-piv4"

# # XXX misisng in ubuntu # to display a list of critical bugs prior to each APT installation. [CUST-0810]
- name: pkgs_debian; install apt-listbugs
  apt:
    pkg:
      - apt-listbugs
    state: present
  when: ansible_host != "invadelabs.com"

## install ntopng AND nut for ups
- name: pkgs_debian; drew-piv3 NUT for UPS and ntopng
  apt:
    pkg:
      - ntopng
      - nut
      - nut-client
      - nut-server
    state: present
  when: ansible_host == "drew-piv3"
  notify:
    - Start nut-driver.service
    - Start nut-server.service
    - Start nut-monitor.service

## invadelabs.com requirements
- name: pkgs_debian; invadelabs.com
  apt:
    pkg:
      - rclone
      - apache2
      - libapache2-mod-php
      - php-sqlite3 # for drewwiki
      - php-mbstring # for drewwiki
      - php-xml
      - php-curl # for selenium-invadelabs script
      - php-apcu # Alternative PHP Cache (APC)
    state: present
  notify:
  - Start apache2.service
  when: ansible_fqdn == "invadelabs.com"

## no pxz in u20.04, u18.04 pxz works though
- name: pkgs_debian; download pxz deb
  get_url:
    url: https://launchpad.net/ubuntu/+archive/primary/+files/pxz_4.999.99~beta5+gitfcfea93-2_amd64.deb
    dest: /root/installers/pxz_4.999.99~beta5+gitfcfea93-2_amd64.deb
    force: no
    owner: root
    group: root
    mode: 0644
    checksum: "sha256:b9534ca34263b8fa9c12f700855f07de1797e43de3f9f157ffd07ffadfc28185"
  when: ansible_fqdn == "invadelabs.com"

- name: pkgs_debian; install pxz deb
  apt:
    deb: /root/installers/pxz_4.999.99~beta5+gitfcfea93-2_amd64.deb
  when: ansible_fqdn == "invadelabs.com"

## mod_pagespeed
- name: pkgs_debian; download mod_pagespeed
  get_url:
    url: https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_amd64.deb
    dest: /root/installers/mod-pagespeed-stable_current_amd64.deb
    force: no
    owner: root
    group: root
    mode: 0644
    checksum: "sha256:14de0b868f4da98bdfdf9cd8e2c12e3abc2a93029168ea27bfb3eb5ea158e3a5"
  when: ansible_fqdn == "invadelabs.com"

- name: pkgs_debian; install mod_pagespeed
  apt:
    deb: /root/installers/mod-pagespeed-stable_current_amd64.deb
  when: ansible_fqdn == "invadelabs.com"

## filebeat (for apache logs)
- name: pkgs_debian; download filebeat deb
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.2.4-amd64.deb
    dest: /root/installers/filebeat-6.2.4-amd64.deb
    force: no
    owner: root
    group: root
    mode: 0644
    checksum: "sha256:003c3a49450c30f3c92543226108a99dfaf70f8eca5869b30d0f31859a23e010"
  when: ansible_fqdn == "invadelabs.com"

- name: pkgs_debian; install filebeat deb
  apt:
    deb: /root/installers/filebeat-6.2.4-amd64.deb
  when: ansible_fqdn == "invadelabs.com"
  notify: Start filebeat.service
