---
  - name: pkgs; mkdir /root/installers
    file:
      path: /root/installers
      state: directory

  - name: pkgs; debconf; postfix; option type 'Internet with smarthost'
    debconf: name=postfix question="postfix/main_mailer_type" value="'Internet with smarthost'" vtype="string"

  - name: pkgs; debconf; postfix; option type 'System mail name'
    debconf: name=postifx question="postfix/mailname" value="invadelabs.com" vtype="string"

  - name: pkgs; install packages
    apt: name={{item}} state=present # update_cache=yes
    with_items:
    - mailutils
    - postfix
    - libsasl2-modules # needed for postfix sendgrid

    - vim
    - logwatch
    - curl # for invadelabs/cron-invadelabs
    - highlight # for invadelabs/cron-invadelabs
    - lynis # for invadelabs/cron-invadelabs/check_lynis.sh
    - bc # for invadelabs/cron-invadelabs/wiki_to_md.sh
    - pandoc # for invadelabs/cron-invadelabs/wiki_to_md.sh
    - pxz # for invadelabs/cron-invadelabs/gdrive.sh
    - gawk # for lynis and ansi2html
    - dbus # for lynis and ansi2html
    notify:
    - Start apache2.service
    - Start postfix.service

  - name: pkgs; certbot
    apt: name={{item}} state=present
    with_items:
      - snapd # for invadelabs/cron-invadelabs/gdrive.sh

      - apache2
      - libapache2-mod-php
      - php-sqlite3
      - php-mbstring
      - php-xml
      - php-curl
      - php-apcu

      - certbot
      - python-certbot-apache
    when: ansible_host == "invadelabs.com"

  - name: pkgs; etckeeper post-install
    shell: |
      touch /var/log/firstpkg.run
      etckeeper post-install
    args:
      creates: /var/log/firstpkg.run

  - name: initial; update-alternatives editor to vim-basic
    alternatives:
      name: editor
      path: /usr/bin/vim.basic
    when: ansible_os_family == 'Debian'
