---
- name: postfix_relay; /etc/postfix/main.cf
  template:
    src: templates/etc/postfix/main-relay.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: Restart postfix.service
