---
  - name: postfix; /etc/postfix/main.cf
    lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^{{item.key}}"
      line: "{{item.key}} = {{item.value}}"
      state: present
      # validate: "postconf -n" # XXX requires %s present but -c uses directory
    with_dict: {
      "smtpd_relay_restrictions": "permit_mynetworks permit_sasl_authenticated defer_unauth_destination",
      "myhostname": "invadelabs.com",
      "alias_maps": "hash:/etc/aliases",
      "alias_database": "hash:/etc/aliases",
      "myorigin": "/etc/mailname",
      "mydestination": "invadelabs.com, $myhostname, localhost",
      "relayhost": "[smtp.sendgrid.net]:2525",
      "mynetworks": "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128",
      "mailbox_size_limit": "0",
      "recipient_delimiter": "+",
      "inet_interfaces": "all",
      "inet_protocols": "all",

      "mtp_tls_security_level": "encrypt",
      "smtp_sasl_auth_enable": "yes",
      "smtp_sasl_password_maps": "hash:/etc/postfix/sasl_passwd",
      "header_size_limit": "4096000",
      "smtp_sasl_security_options": "noanonymous"
      }
    notify: Restart postfix.service

  - name: postfix; set sasl_passwd
    shell: cat /root/postfix_passwd
    register: sasl_passwd

  - name: postfix; create /etc/postfix/sasl_passwd
    copy:
      dest: /etc/postfix/sasl_passwd
      mode: 0600
      content: "{{ sasl_passwd.stdout }}"
    creates: /etc/postfix/sasl_passwd.db

  - name: postfix; postmap /etc/postfix/sasl_passwd
    shell: |
      postmap /etc/postfix/sasl_passwd
      rm /etc/postfix/sasl_passwd
    args:
      chdir: /etc/postfix
      creates: /etc/postfix/sasl_passwd.db
    notify: Restart postfix.service
