---
- debug:
    msg: "preflight_check; passwd pi; useradd -m -k drew; passwd drew; sudo visudo; sudo vi /etc/hosts 192.168... drew-piv4; sudo hostnamectl set-hostname drew-piv4.blabla;"

- name: preflight_check; fail if hostname not set
  fail:
    msg: "Host name {{ansible_fqdn}} is not set. Run; hostnamectl set-hostname invadelabs.com"
  when: ( ansible_fqdn == "localhost" ) or ( ansible_fqdn == "raspberrypi" ) or ( ansible_fqdn == "pine64" )

- name: preflight_check; invadelabs.com stat required files in /root
  stat:
    path: "{{invadelabs_file_item}}"
  with_items:
    - /root/apache_env
    - /root/github_token
    - /root/postfix_passwd
    - /root/slacktee.conf
    - /etc/default/cgm.env
    - /home/drew/home_ip
  loop_control:
    loop_var: invadelabs_file_item
  register: item
  # failed_when: item.stat.exists == False # mode below implies file exists
  failed_when: item.stat.mode != '0400'
  when: ansible_host == "invadelabs.com"

- name: preflight_check; ensure tunnel key is in authorized_keys
  shell: grep tunnel_2020.05.17 /home/drew/.ssh/authorized_keys
  when: ansible_host == "invadelabs.com"
  changed_when: false

- name: preflight_check; drew-serv stat required files in /root
  stat:
    path: "{{drewserv_file_item}}"
  with_items:
    #- /root/google_ddns.cred
    - /root/cloudflare_ddns.cred
    - /root/postfix_passwd
    - /root/slacktee.conf
    - /home/drew/.ssh/tunnel_2020.05.17
    - /etc/default/ring-mqtt.env
    - /root/healthchecks.io
  loop_control:
    loop_var: drewserv_file_item
  register: item
  failed_when: item.stat.exists == False # XXX ensure set 0400, figure out *.env as required group 0440
  when: ansible_host == "drew-serv"

- name: preflight_check; /etc/hosts has IP, hostname, and fqdn
  shell: grep {{ansible_default_ipv4.address}} /etc/hosts | grep {{ansible_host}} | grep {{ansible_fqdn}} && touch /var/log/hosts-init.touch
  args:
    chdir: /root
    creates: /var/log/hosts-init.touch
  register: hosts_rc
  failed_when: hosts_rc.rc != 0 # rc = proccess exit code
  when: ansible_host != "invadelabs.com"

- name: preflight_check; if rclone initalized
  shell: rclone listremotes | grep "googledrive:" && touch /var/log/rclone-init.touch
  args:
    chdir: /root
    creates: /var/log/rclone-init.touch
  register: rclone_stat
  failed_when: rclone_stat.rc != 0 # rc = proccess exit code
  when: (ansible_host == "drew-serv") or (ansible_host == "invadelabs.com")

- debug:
    msg: "Run `cd /srv/docker-elk; docker-compose up -d` after restoring /srv/data if we fail around here."

- name: preflight_check; ensure folders exist
  stat:
    path: "{{ drewserv_folder_item }}"
  with_items:
    - /srv/data
    - /mnt/share/bkup
    - /mnt/share/nexus-data
  loop_control:
    loop_var: drewserv_folder_item
  register: item
  failed_when: item.stat.exists == False
  when: ansible_host == "drew-serv"
