---
- name: samba; smb.conf # XXX add smb users here / better unix password sync; smbpasswd -a drew && smbpasswd -e drew
  template:
    src: templates/etc/samba/smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
    validate: /usr/bin/testparm -s %s
  notify: Restart smbd.service
