---
- name: samba; smb.conf
  copy:
    src: templates/etc/samba/smb.conf
    dest: /etc/samba/smb.conf
    validate: /usr/bin/testparm -s %s
  notify: Restart smb.service
  # XXX add smb users here / better unix password sync
  # smbpasswd -a drew
  # smbpasswd -e drew
