---
- name: ufw; allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH
    comment: SSH

- name: ufw; allow WireGuard
  ufw:
    rule: allow
    route: yes
    interface_in: wg0
    interface_out: eno1
    comment: WireGuard

- name: ufw; allow 25/tcp
  ufw:
    rule: allow
    comment: Postfix
    port: 25
    src: 192.168.1.0/24

- name: ufw; allow 53/udp
  ufw:
    rule: allow
    comment: DNS
    port: 53
    proto: udp

- name: ufw; allow 80/tcp
  ufw:
    rule: allow
    comment: http
    port: 80
    proto: tcp

- name: ufw; allow 111/tcp
  ufw:
    rule: allow
    comment: something microsoft
    port: 111

- name: ufw; allow 137:138
  ufw:
    rule: allow
    comment: samba
    port: 137:138
    proto: udp
    src: 192.168.1.0/24

- name: ufw; allow 139/tcp
  ufw:
    rule: allow
    comment: something microsoft
    port: 139
    proto: tcp
    src: 192.168.1.0/24

- name: ufw; allow 443/tcp
  ufw:
    rule: allow
    comment: https
    port: 443
    proto: tcp

- name: ufw; allow 445/tcp
  ufw:
    rule: allow
    comment: something microsoft
    port: 445
    proto: tcp
    src: 192.168.1.0/24

- name: ufw; allow 1883/tcp
  ufw:
    rule: allow
    comment: Mosquito
    port: 1883
    proto: tcp
    src: "{{ mosquito_item }}"
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: mosquito_item

- name: ufw; allow 3000/tcp
  ufw:
    rule: allow
    comment: Grafana
    port: 3000
    proto: tcp
    src: "{{ grafana_item }}"
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: grafana_item

- name: ufw; allow 3493/tcp
  ufw:
    rule: allow
    comment: nut-server
    port: 3493
    proto: tcp
    src: "{{ nut_item }}"
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: nut_item

- name: ufw; allow 10514,5000/tcp
  ufw:
    rule: allow
    comment: es-logstash
    port: 10514,5000
    proto: tcp
    src: "{{ es_logstash_item }}"
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: es_logstash_item

- name: ufw; allow 5080/tcp
  ufw:
    rule: allow
    comment: zigbee2mqtt
    port: 5080
    proto: tcp
    src: 192.168.1.0/24

- name: ufw; allow 5601/tcp
  ufw:
    rule: allow
    comment: Kibana
    port: 5601
    proto: tcp
    src: "{{ kibana_item }}"
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: kibana_item

- name: ufw; allow 5666/tcp
  ufw:
    rule: allow
    comment: nrpe
    port: 5666
    proto: tcp
    src: '{{ nrpe_item }}'
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: nrpe_item

- name: ufw; allow 8080/tcp
  ufw:
    rule: allow
    comment: drew-serv-http
    port: 8080
    proto: tcp
    src: '{{ drew_serv_http_item }}'
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: drew_serv_http_item

- name: ufw; allow 8081,8181,8183,8184,8185/tcp
  ufw:
    rule: allow
    comment: nexus
    port: 8081,8181,8183,8184,8185
    proto: tcp
    src: '{{ nexus_item }}'
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: nexus_item

- name: ufw; allow 8086/tcp
  ufw:
    rule: allow
    comment: influxdb
    port: 8086
    proto: tcp
    src: '{{ influxdb_item }}'
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: influxdb_item

- name: ufw; allow 8123/tcp
  ufw:
    rule: allow
    comment: homeassistant
    port: 8123
    proto: tcp
    src: '{{ homeassistant_item }}'
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: homeassistant_item

- name: ufw; allow 9090/tcp
  ufw:
    rule: allow
    comment: prometheus
    port: 9090
    proto: tcp
    src: '{{ prometheus_item }}'
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: prometheus_item

- name: ufw; allow 9100/tcp
  ufw:
    rule: allow
    comment: prometheus-node-exporter
    port: 9100
    proto: tcp
    src: '{{ prometheus_node_exporter_item }}'
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: prometheus_node_exporter_item

- name: ufw; allow 9199/tcp
  ufw:
    rule: allow
    comment: prometheus-nut-exporter
    port: 9199
    proto: tcp
    src: '{{ prometheus_nut_exporter_item }}'
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: prometheus_nut_exporter_item

- name: ufw; allow 8324,32400,32469/tcp
  ufw:
    rule: allow
    comment: plex-tcp
    port: 8324,32400,32469
    proto: tcp
    src: '{{ plex_item }}'
  with_items:
    - 172.17.0.0/16 # XXX re-network
    - 192.168.1.0/24
  loop_control:
    loop_var: plex_item

- name: ufw; allow 1900,5353,32410,32412,32413,32414/udp
  ufw:
    rule: allow
    comment: plex-udp
    port: 1900,5353,32410,32412,32413,32414
    proto: udp
    src: 192.168.1.0/24
